[STEP 1] ERA, POODLE
tasty-code/ios-calculator pull request #1
Opened 2022-09-06 02:53 UTC by kr-yeon

@jaemuYeo 리뷰 부탁드립니다!

### **역할**
드라이버: @parseyoon
네비게이터: @kr-yeon

### **수행한 내용**
- [x] Unit Test 추가
- [x] Queue 타입과, CalculatorItemQueue 를 UML로 표현
- [x] Queue 타입과, CalculatorItemQueue추가
- [x] CalculateItem 생성 및 준수

### **고민되었던 내용**
UML 짤 때부터 고민했습니다. Queue의 역할이 무엇이고, 어떻게 동작을 할지 고민을 하기도 하였고, 검색을 하며 Queue에 대한 내부 메서드 또한 생성하였습니다. Queue의 역할과 List와의 차이점이 많이 고민되었지만, 이 고민은 지금도 그대로 남아있습니다.

### **조언을 얻고싶은 부분**
Queue의 명확한 사용성과 이점이 궁금합니다. 이번 프로젝트에서 Queue라는 점을 강조해서 사용하고 만들어보라고 하셔서, 찾아 만들어 보았지만, 이 조언에 대한 답이 나오지 못한 상태입니다. 제일 중요한 부분이라고 생각되기도 하고요. Queue의 이점과 동작에 대해서 조언을 얻을 수 있을까요?

2022-09-06 07:33 UTC, jaemuYeo requested changes
에라 푸들 계산기 프로젝트에 오신걸 환영합니다 ㅎㅎ 😀
이번 스텝은 몇가지 자료구조와 시간복잡도 등에 대해 이해하고 넘어가면 좋아요!
고민했던 큐와 리스트의 차이점을 알아보기보다는 리스트를 통한 큐타입 구현으로 
생각해주면 좋을 것 같습니다!
일반적인 큐타입을 사용했을 때와 리스트를 활용한 큐타입의 이점이 어떤것들이 있을까요??
[참고자료](https://woongsios.tistory.com/222) 남겨드릴게요!
같이 꼭 이해하고 넘어가면 좋을 것같아요~

----
## 코드 개선해야할 부분
현재 테스트파일 내부에 타입들이 구현이 되어있어요!
테스트파일은 말그대로 타입을 설계한 것에대한 테스트를 진행하는 곳입니다
저번에 활용했던 MVC별 그룹과 파일을 분리해서 타입의 위치를 변경해주세요! 😀
(Test 진행에 있어 감이 잡히지 않으면 저를 회의실로 불러주세요!)
Test 케이스에는 `given when then 패턴`을 조사하고 활용해보세요 💪

## 동작방식
동작 방식은 에라와 푸들이 같이 맥 또는 아이폰 계산기앱을 켜서 한번 고민해보면 좋을 것같아요!
내가 누른 숫자와 연산자가 어떻게 담기고 어떻게 빠져나와 다시 결과값을 저장하는지요
고민 후에 궁금증이 풀리지 않으면 불러주세요!

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +enum ValueError : Error {
앞으로도 여러 에러들이 정의될텐데 값에 대한 에러를 위한 타입명보다는
현재 프로젝트 (Calculator)에 대한 에러타입으로 하면 어떤가요??
Hint. Naming

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +struct CalculatorItem {
이 타입은 무엇을 하는 역할인가요? 프로토콜로 선언된 CalculatorItem과 다른 건가요?

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +class Queue<T> {
class로 선언한 이유가 있나요??

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var list: [T]
여기에 `var list: [T] = []` 형태로 초기화 할 수도 있는데 init을 통해 빈배열을 할당한 이유가 있나요?

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        get {
get을 사용하지 않아도 될것같아요 😀

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        return self.count == 0
list에 요소가 있는지 없는지를 판단하는 기능인데
```swift
return list.isEmpty
```
만으로도 체크할 수 있을 것같아요!

2022-09-06 07:33 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +class CalculatorItemQueue : Queue<CalculatorItem>, CalculateItem {
현재 타입의 네이밍이 `CalculatorItemQueue`로 말그대로 Queue타입을 구현하는 곳인데
다른 곳에서 Queue타입을 구현한 이유가 무엇인가요🤔

2022-09-07 02:25 UTC, kr-yeon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +class CalculatorItemQueue : Queue<CalculatorItem>, CalculateItem {
처음에는 큐라는 타입은 공통적으로 쓰기때문에, Queue라는 것을 따로 만드는게 좋다고 생각하였습니다.
하지만 STEP 1의 내용을 다시 확인해본바, 큐 타입은 CalculatorItemQueue안에서 구현하는 것이였습니다. 잼킹께서 주신 참고자료를 활용하여 코드 수정해았습니다!

2022-09-07 02:27 UTC, parkseyoon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        return self.count == 0
Swift의 Array에 대한 문법이 아직 어색하여 생긴 문제입니다..!
코드 수정하였습니다!

2022-09-07 07:19 UTC, jaemuYeo requested changes
커밋메시지를 잘 남겨주어서 수정된 부분을 쉽게 파악할 수 있었어요! 👍💯
코드에 개별 코멘트 남겨놓았습니다!
수정해보면서 여러 테스트케이스들을 통해 Unit Test도 진행해주세요!

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/Error.swift
> +enum CalculatorError : Error {
별도로 관리하는거 좋아요 👍

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
간단한 요소를 확인하는 거라면 연산프로퍼티로 해주어도 됩니다!

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func count() -> Int {
간단한 요소를 확인하는 거라면 연산프로퍼티로 해주어도 됩니다!

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func peak() throws -> T {
peek의 오타일까요?
이것도 에러를 처리하기보다는 반환타입을 옵셔널로 주고
필요한 부분의 값을 return하면 좋을 것같네요!

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        return list.removeFirst()
메서드에 반환타입이 있더라도 이렇게 단행함수는 return 키워드를 없애도 된답니다!
적어도 같은 파일 내부에서는 통일된 모습으로 관리해주세요~

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> T {
디큐의 경우 list에 값이 없다면 어떻게 되나요?
반환타입을 어떻게 해볼 수 있을까요?

2022-09-07 07:19 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +protocol CalculateItem {
이것도 따로 파일을 분리해두면 좋을것같네요!

2022-09-08 00:39 UTC, kr-yeon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        return list.removeFirst()
dequeue는 큐의 앞에서 원소를 삭제하여 반환하는것으로 알고 있습니다. 그래서 제일 앞 원소를 제거하며 반환하기 위해 return하였습니다.

2022-09-08 01:14 UTC, jaemuYeo requested changes
TDD진행해주세요!! 테스트 진행후 재요청주시면 머지하겠습니다~
테스트 후에 다음스텝으로 가지않고 [참고자료](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift/v4.0/chapters/8-queues)를 보며
두분이 구현한 큐타입을 되돌아보는 시간을 가져주세요!

2022-09-08 01:14 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws -> T {
에러를 던지지 않고 처리할 수 있는 방법은 없을까요??
많이 쓰이는 함수인데 꺼내쓸때마다 매번 에러처리를 해야하겠군요 🤔
전에 전달했던건 '반환타입을 옵셔널로 하면 어떨까?' 에 대한 제시였는데
두분은 어떻게 생각하시나요?? (peek도 포함되는 내용입니다)

2022-09-08 01:17 UTC, kr-yeon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws -> T {
에러 메시지를 명확히 표시하고 싶습니다. try? 를 통해 에러 발생시 옵셔널로 처리하게 만들면 어떨까요?

2022-09-08 02:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws -> T {
왜 에러가 발생할때에 옵셔널로 처리를 하게끔 두번 일을 하나요??
T? 를 반환하면 값이 있으면 디큐를 할테고 없으면 nil을 반환할텐대요!

2022-09-08 02:25 UTC, jaemuYeo requested changes
재요청 천천히해도 됩니다,, 충분한 학습후 반영해서 요청해주세요 부탁입니다 🙏
속도가 중요한게 아니예요‼️
참고문서에 있던 [Unit test](https://yagom.net/courses/unit-test-%ec%9e%91%ec%84%b1%ed%95%98%ea%b8%b0/) 를 학습하고
TDD를 다시 진행해보세요 💪

2022-09-08 03:02 UTC, kr-yeon commented
TestCase의 함수 네이밍중 한글로 'testQueue에많은원소가추가되어도dequque가된다'라고 할때 띄어쓰기 등 네이밍의 원칙은 어떻게 하는게 좋을까요?

2022-09-08 05:15 UTC, jaemuYeo reviewed
에라 푸들 스텝1 고생많았습니다!! 👏
머지진행할게요!!
추가적으로 수정할 부분은 다음 스텝을 진행하면서 보완해나가보세요!
질문주신 테스트케이스에 대한 네이밍은 보통 언더바로 띄어쓰기를 표시합니다😀

2022-09-08 05:15 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +
테스트에 정답은 없지만 함수 내부에서의 진행의 흐름이 조금 더 명확했으면 좋겠어요!
given - 무언가 주어질때
when - 어느순간에
then - 결과가 나온다
를 상수에 적절히 넣어서
여러 Assert함수의 매개변수에 넣으면 좋을 거같아요 😃

2022-09-08 05:15 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func testQueue에많은원소가enqueue된다() {
보통 이런 테스트 보다는 `큐에_인큐를두번하면_카운트는_2다` 처럼 진행한답니다!

2022-09-08 05:15 UTC, merged