[STEP 2] Rookie, Ireu
tasty-code/ios-calculator pull request #10
Opened 2022-09-13 06:21 UTC by Y00ujin

@jaemuYeo  리뷰 부탁드려요

### 수행한 부분
- #### formula 구조체 구현
- #### ExpressionParser 열거형 구현
- #### Operator 열거형 구현

<br>

### 궁금한 부분
- #### ExpressionParser 열거형의 componentsByOperators(from input:) 함수의 용도를 파악하지 못했어요.

2022-09-13 08:55 UTC, jaemuYeo requested changes
루키 이르 Step2도 빠르게 진행해주었네요!! 👍
지정된 UML을 보며 타입설계를 했을때 어떤 느낌이었나요??
코드에 대한 부분은 코멘트를 통해 전달할게요~

‼️ UnitTest에 대한 최신화가 되어있지 않네요!
Queue타입이 사라지며 발생한 에러같습니다 😀

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<Element>: CalculatorItem {
큐 타입이 사라지고 CalculatorItemQueue에서 큐타입 구현을 하였군요!
UML에서는 이 큐타입을 구조체로 선언하라고 되어있는데 클래스로 선언한 이유가있나요??
큐타입을 구조체로 요구한 이유는 무엇일까요?

UML과 다른 프로토콜 채택이 있군요! 👀

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
>  protocol CalculatorItem {
이 프로토콜 따로 그룹을 나누어 관리하면 좋을거같아요~

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +extension Double: CalculatorItem {
같은 파일에 있는 객체에 대한 확장이 아닌경우
```swift
// 같은 파일의 객체에 대한 확장
class ViewController: UIViewContriller {

}

extension ViewController {

}
```
Extension 그룹을 만들어 관리하는 것이 좋아요~
Extension 파일은 보통 객체이름+extension으로 지정합니다!
`String+extension`

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) -> Formula {
UML에서 밑줄은 무엇을 뜻할까요??

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = CalculatorItemQueue<Character>()
이 곳에 CalculatorItemQueue의 제네릭 타입도 Operator이면 명확할 거같아요 😀

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    private func componentsByOperators(from input: String) -> [String] {
UML에서 밑줄은 무엇을 뜻할까요??

주석과 고민한점에 작성했듯 이 메서드에 대한 궁금증이 있을텐데요!
private 메서드라는 것은 parse메서드에서 사용할 도구라는 것을 알수있겠죠??
메서드를 기능분리 하기 위해 요구한 사항입니다.
네이밍 그대로 연산자를 구성하게 하는 메서드입니다~

메서드가 잘 이해되지 않았던 이유를 생각해보면
현재 parse 메서드에서 배열의 0, 1, 2 인덱스에 대한 것을 연산자와 피연산자로 구분지어놨는데
3, 4, 5 ,,,,, 인덱스에 대한 계산은 어떻게 처리하는지 수정하다보면 
이 메서드가 왜 필요한지 알수도 있을 것같아요!!
한 번 시도해보고 막히면 다시 디엠주세요 💪

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +    var operands: CalculatorItemQueue<Double>
복수형 네이밍 나이스입니다 💯

단 유저가 계산기 내부에 연산자와 피연산자에 접근이 가능할까요?

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Character>
CalculatorItemQueue안의 제네릭 타입이 Character보다는 Operator가 조금 더 명확하지 않을까요?
Operator타입을 보니 rawValue가 Character군요!

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +    func result() -> Double {
현재 이 메서드는 두개의 큐에서 값을 꺼내와 단순계산만 하고있군요!
몇 가지 기능이 더 필요할 거같아요~
1. 만약 큐가 비어있다면 어떻게 되나요?
2. 연산자와 피연산자가 큐에 담겼지만 피연산자가 하나인 경우는 어떻게 될까요?
3. 여러 연산자와 피연산자가 담겨있을 경우 한번만 계산하나요?

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +        guard let lhs = operands.dequeue(), let rhs = operands.dequeue(), let _operator = operators.dequeue(),
예약어인 operator 때문에 언더바를 통해 네이밍 하기보단
```
`operator`
```
를 통해 에약어를 피할 수 있는 방법도 있답니다!

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Operator.swift
> +    private func divide(_ lhs: Double, _ rhs: Double) -> Double {
요구사항을 보면 0으로 나누기를 할 경우 특정 에러를 발생하고 있습니다
어떻게 처리해볼 수 있을까요?

2022-09-13 08:55 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +            return 0
만약 0이 리턴되어 나누기가 된다면 어떻게 될까요?
dequeue과정에서 처리해보면 좋을 거같아요!

2022-09-14 04:47 UTC, Y00ujin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<Element>: CalculatorItem {
왜 구조체로 선언된 건지 잘 모르겠습니다 ㅠㅠ!!

2022-09-14 04:48 UTC, Y00ujin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
>  protocol CalculatorItem {
다른 파일로 분리하라는 말씀이실까요?

2022-09-14 04:49 UTC, Y00ujin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +extension Double: CalculatorItem {
수정했습니다!

2022-09-14 04:51 UTC, Y00ujin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) -> Formula {
private! 수정했어요

2022-09-14 04:52 UTC, Y00ujin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = CalculatorItemQueue<Character>()
수정했어요!

2022-09-14 04:54 UTC, Y00ujin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) -> Formula {
아 static..!

2022-09-14 05:22 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
>  protocol CalculatorItem {
넵! Protocol이라는 그룹을 만들고 그 안에 파일분리를 하면 좋을 거같아요 😀

2022-09-14 06:58 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    private func componentsByOperators(from input: String) -> [String] {
수정했습니다

2022-09-14 07:09 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Character>
넵 수정하였습니다

2022-09-14 08:03 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/Formula.swift
> +    func result() -> Double {
큐가 비어있거나 연산자와 피연산자의 개수가 계산을 하지 못하는 상황일 때의 에러 처리를 구현했습니다

2022-09-14 08:03 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/Formula.swift
> +        guard let lhs = operands.dequeue(), let rhs = operands.dequeue(), let _operator = operators.dequeue(),
넵 수정하겠습니다

2022-09-14 08:22 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/Operator.swift
> +    private func divide(_ lhs: Double, _ rhs: Double) -> Double {
swift 에서 0으로 나누는 경우 infinity를 반환하기에 Double의 메서드인 isInfinity를 사용하여 infinity인 경우 에러 처리를 하도록했습니다

2022-09-14 08:24 UTC, chaeyoon1101 commented on Calculator/Calculator/Model/Formula.swift
> +            return 0
해결해보겠습니다

2022-09-15 03:26 UTC, jaemuYeo reviewed
루키 이르 스텝2도 고생많았어요!!
로직상 큰 문제는 없기에 이번스텝 머지 진행하겠습니다!
몇 가지 코멘트 남겨놓았으니 확인부탁해요 😀

타입별로 다양한 테스트케이스를 만들어 TDD를 진행한 부분은 너무너무너무너무 칭찬하고싶네요 👏
테스트를 해보며 구현한 코드에 대해 자신감이 붙었나요? 🙂

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element>: CalculatorItem {
이 구조체는 CalculatorItem 프로토콜을 채택하지 않습니다 🙅‍♂️

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/Error/CalculateError.swift
> +enum CalculateError: Error {
적절한 에러타입 좋아요 💯

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/Error/CalculateError.swift
> +    case impossibleCalculate
이 에러는 0으로 나눴을때에 대한 케이스인가요??
만약 맞다면 `dividedByZero`와 같은 명확한 네이밍도 좋습니다!
"NaN"에 대한 처리도 해주면 좋을 것같아요~

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    static func parse(from input: String) -> Formula {
내부로직 잘 구현해주었네요!!
다만 Operator 타입이 CaseIterable을 채택했는데 그것에 대한 활용을 해보지 않은것이 조금은 아쉽습니다 😀

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operands = componentsByOperators(from: input).compactMap { Double($0) }
componentsByOperators(from: input)
이것도 상수에 저장했다면 코드의 길이를 조금 줄일수 있었을 것같아요!

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let splitedInput = input.split(with: " ")
상수에 담아 리턴하는 형식 너무 좋습니다 👍

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.isEmpty == false || operators.isEmpty == false {
이제는 큐에 대한 모든 값을 처리할 수 있겠네요!! 👏
코드가 너무 길어진다면 적절히 끊어주는 것도 좋아요~ 
```swift
while operands.isEmpty == false || operators.isEmpty == false {
    if let rhs = operands.dequeue(),
       let `operator` = operators.dequeue()?.rawValue,
       let calculatedValue = try Operator(rawValue: `operator`)?.calculate(lhs: result, rhs: rhs) {
        result = calculatedValue
    } else {
        throw CalculateError.impossibleCalculate
    }
}
```

2022-09-15 03:26 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +               let calculatedValue = try Operator(rawValue: `operator`)?.calculate(lhs: result, rhs: rhs)  {
중괄호가 두번 띄어쓰기 된 곳이 있네요!

2022-09-15 03:26 UTC, merged