[Step2] 재근, 도도
tasty-code/ios-calculator pull request #12
Opened 2022-09-14 07:02 UTC by wormsJJG

# 수행한 내용
- UML에 따라 타입구현
- 연산식을 쪼개 배열에 넣어주는 함수 구현
- 연사자와 피연산자를 나누어 Formula를 생성해 반환하는 함수구현

2022-09-14 09:40 UTC, jaemuYeo requested changes
재근 도도 스텝2도 고생많았습니다!!
UML을 보며 타입설계를하니 조금은 편하지않았나요?? ㅎㅎ
코드에 대한 부분은 코멘트를 통해 전달하겠습니다!

CalculatorTests파일에 필요없는 주석과 함수는 지워도 될거같아요!
다음번에는 given when then 패턴을 이용하여 테스트의 흐름을 조금 더 명확하게 해보세요~
테스트 케이스 네이밍도 한 번 더 고민해보면 좋을거같아요 ☺️
```swift
// 아래 주석은 허용입니다

func test_빈배열에_1을인큐하고_디큐했을때_디큐한값은1이다() {
    // given
    given에 대한 코드
    // when
    when에 대한 코드
    // then
    then에 대한 코드
}
```

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Error/CalculatorError.swift
> +enum TypeConversionError: Error {
파일명은 CalculatorError인데 타입명은 다르군요!
새로운 에러가 추가될때마다 새로운 타입을 만들건가요?? 🤔
제 생각에는 CalculatorError이라는 열거형타입에
이 프로젝트에서 발생하는 계산기 동작에 대한 모든 에러를 관리하면 좋을 거같아요!
에러를 표시할때는 `localizederror`와 `error errordescription`에 대해 알아보고 적용해보면
신세계를 느낄겁니다 ㅎㅎ

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Extension/Double+Extension.swift
> +extension Double {
UML과 다른 것이 있네요!

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Extension/String+Extension.swift
> +    func split(with target: Character) -> [String] {
메서드를 적절하게 구현해주었네요! 좋아요 👍

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func dequeue() -> T? {
CalculatorItemQueue타입 내부에 있는 은닉화를 제외한 프로퍼티나 메서드는
internal로 접근제어를 설정해도 다른 파일 또는 객체에서 충분히 접근될 것같아요!!

디큐를 진행할때 내부적으로 에 값이 있다면 removeFirst를 진행할텐데
idx를 1 증가시키는 로직을 구현한 이유는 무엇인가요?

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) throws -> Formula {
UML에서 밑줄로 표시된 것은 어떤것일까요??

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var operands = CalculatorItemQueue<Double>()
Fromula타입에도 비슷한 형태의 프로퍼티가 있는데 인스턴스를 만들어서 사용하면 어떨까요?
(선택사항입니다!)

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var operators = CalculatorItemQueue<Character>()
Operator타입도 rawValue가 Character입니다
어떻게 바꿔볼 수 있을까요?

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        for i in 0..<formula.count {
componentsByOperators를 통해 연산자와 피연산자를 `구분`해서 넣어주는 과정만 있으면 될것같아요
고차함수들을 활용하면 정말 간결하게 표현될겁니다!

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            let operands: [String] = input.components(separatedBy: ["+", "-", "/", "*"])
저희 저번시간에 CaseIterable을 채택한 열거형을 allCases 등등으로 다양하게 구현해보았어요!
이 곳에서도 활용해 볼수있을 것같아요 😀
괜찮다면 forEach와 같은 고차함수도 적절히 사용해보세요!

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Character>
Operator타입도 rawValue가 Character입니다
어떻게 바꿔볼 수 있을까요?

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +        guard let lhs = operands.dequeue(), let rhs = operands.dequeue(), let operators = operators.dequeue(), let result = Operator(rawValue: operators)?.calculate(lhs: lhs, rhs: rhs) else {
너무 길어지는 코드는 가독성에 좋지않아요 🙅‍♂️
```swift
mutating func result() -> Double {
    guard let lhs = operands.dequeue(),
          let rhs = operands.dequeue(),
          let operators = operators.dequeue(),
          let result =
            Operator(rawValue: operators)?.calculate(lhs: lhs, rhs: rhs)
    else {
        return 0
    }
    return result
}
```
적절한 개행을 해주면 좋습니다 😀

현재 로직은 단 한번만의 계산결과를 리턴하고있네요!
큐에 만은 연산자와 피연산자가 담겨있어도 두개의 피연산자와 하나의 연산자만을 꺼내서 계산하고
종료될 거같아요 🤔
만약 피연산자랑 연산자가 하나일 경우에 이 함수를 실행시키면 어떻게 되나요?

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/Formula.swift
> +            return 0
만약 0을 리턴했을때 연산자가 나누기라면 어떻게 될까요??

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/Operator.swift
> +    private func divide(lhs: Double, rhs: Double) -> Double {
0으로 나누면 어떤 결과가 나오죠?
이 곳에서 에러처리를 해주면 좋을 것같아요 🤔

2022-09-14 09:40 UTC, jaemuYeo commented on Calculator/Calculator/Model/Operator.swift
> +
불필요한 개행이 있네요!

2022-09-15 00:58 UTC, wormsJJG commented on Calculator/Calculator/Error/CalculatorError.swift
> +enum TypeConversionError: Error {
넵 충분히 공부후 적용해보겠습니다!

2022-09-15 00:59 UTC, wormsJJG commented on Calculator/Calculator/Extension/Double+Extension.swift
> +extension Double {
UML에도 Double을 Extension한 부분이 있는데 확인부탁드립니다!

2022-09-15 00:59 UTC, wormsJJG commented on Calculator/Calculator/Extension/String+Extension.swift
> +    func split(with target: Character) -> [String] {
ㅎㅎ!

2022-09-15 01:01 UTC, wormsJJG commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) throws -> Formula {
readonly 인가요?

2022-09-15 01:01 UTC, wormsJJG commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Character>
Operator타입의 큐를 만드는것이 좋겠네요!

2022-09-15 01:02 UTC, wormsJJG commented on Calculator/Calculator/Model/Formula.swift
> +        guard let lhs = operands.dequeue(), let rhs = operands.dequeue(), let operators = operators.dequeue(), let result = Operator(rawValue: operators)?.calculate(lhs: lhs, rhs: rhs) else {
고민해보겠습니다!

2022-09-15 01:02 UTC, wormsJJG commented on Calculator/Calculator/Model/Formula.swift
> +            return 0
에러가 날것같습니다!

2022-09-15 01:02 UTC, wormsJJG commented on Calculator/Calculator/Model/Operator.swift
> +    private func divide(lhs: Double, rhs: Double) -> Double {
넵

2022-09-15 01:02 UTC, wormsJJG commented on Calculator/Calculator/Model/Operator.swift
> +
수정하겠습니다.!

2022-09-15 01:08 UTC, wormsJJG commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var operands = CalculatorItemQueue<Double>()
참고하겠습니다!

2022-09-15 01:09 UTC, wormsJJG commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        for i in 0..<formula.count {
넵

2022-09-15 01:09 UTC, wormsJJG commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            let operands: [String] = input.components(separatedBy: ["+", "-", "/", "*"])
넵

2022-09-15 01:20 UTC, dddowon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func dequeue() -> T? {
테스트를 진행할 때에 옵셔널로 반환 값을 가지지않기 위해 idx를 1 증가시키는 로직을 구현하였는데 �에 값이 있다는 방향도 생각을 해 로직을 다시 구현해보면 좋을 것  같습니다!

2022-09-15 01:39 UTC, jaemuYeo commented on Calculator/Calculator/Extension/Double+Extension.swift
> +extension Double {
화살표들도 한번 살펴봐주세요 😀

2022-09-15 01:41 UTC, jaemuYeo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    func parse(from input: String) throws -> Formula {
static 입니다!

2022-12-22 07:55 UTC, closed without merging