Calculator [STEP 1] Joo, Lust3r
tasty-code/ios-calculator pull request #13
Opened 2023-01-16 08:23 UTC by llimental

# Calculator [STEP 1] Joo, Lust3r
안녕하세요! 소대(@zdodev)! 이번 Calculator 프로젝트를 진행하게 된 Joo, Lust3r 입니다!
Step1에서는 요구사항이 별로 없어 다음 스텝에서는 동작에 대한 처리를 어떻게 해야할 지 좀 더 고민을 하였습니다. 그래서 프로토콜의 사용법에 관해서 고민한 결과 코드와 같이 구현하게 되었습니다.

앞으로의 프로젝트 진행에 있어 잘 부탁드립니다. 감사합니다 🙇🏼‍♂️

## 🧑🏼‍💻 작업 목록

### STEP 1 : [ 스크럼 ](https://www.notion.so/tastycode/1-16-01fb0ca20cbb4d569c341446a7f9c2ea)

- [x] Queue 타입 구현
    - [x] 프로젝트에 `Unit Test` 타깃 추가
    - [x] 큐 타입으로 `CalculatorItemQueue` 구현, 큐 타입의 UML 표현
        - [x] 다루는 요소는 `CalculateItem` 프로토콜 준수

## 💭 학습 키워드

- discardableResult
- queue
- generic

## 🤔 고민과 해결

- 유닛테스트 시 XCTAssertEqual을 사용할 때 오류가 발생하여 queue에 들어가는 Item에 Equatable 프로토콜을 채택하여 해결하였습니다

## 🙋🏻 질문 거리
- `CalculatorItemQueue`에서 다루는 요소는 `CalculateItem` 프로토콜을 준수합니다.
라는 요구사항이 있는데, 이것이 의미하는게 `ItemQueue`에 들어갈 Item이 준수해야 한다는 것인지 궁금합니다.
- 프로토콜에서는 Value의 타입으로 Numeric을 사용하여 Double과 Int를 묶으려고 하였는데, 이것을 어떻게 활용해야 하는지 궁금합니다.
- UML 작성을 해봤는데, 관계를 나타내는 연결선들이 잘 표현되었는지 궁금합니다.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/45708630/212628077-6cbf9f0f-8ed4-4a78-bc75-642fd7aaa0d7.png">

2023-01-17 14:29 UTC, zdodev requested changes
안녕하세요. @llimental , @ohdair !

Step 1 잘 진행해주셨습니다!🎉
테스트 커버리지를 100% 로 작성해보셨네요.👍

고민과 해결한 부분도 잘 진행해주셨습니다!

질문에 대한 제 생각을 말씀드리면,

❓CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다. 라는 요구사항이 있는데, 이것이 의미하는게 ItemQueue에 들어갈 Item이 준수해야 한다는 것인지 궁금합니다.
- 네. 저도 CalculatorItemQueue에서 다루는 요소(Item)는 CalculateItem 프로토콜을 준수해야 한다고 이해했습니다!

❓프로토콜에서는 Value의 타입으로 Numeric을 사용하여 Double과 Int를 묶으려고 하였는데, 이것을 어떻게 활용해야 하는지 궁금합니다.
- 묶으려고 하시는 이유가 궁금합니다! 피연산자들의 실제 연산을 수행할 수 있을지 고민해보면 좋을 것 같습니다!

❓UML 작성을 해봤는데, 관계를 나타내는 연결선들이 잘 표현되었는지 궁금합니다.
- UML은 enum 타입들의 화살표만 표현된다면 현재 프로젝트 코드에 맞게 잘 작성해주셨습니다.👍

몇 가지 궁금증을 남겨보았습니다!
확인 부탁드립니다~

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Enums.swift
> +enum Toggle {
`Toggle` 은 숫자의 부호를 나타내는 타입일까요?🤔
만약 맞다면, `Toggle` 의 의미로는 부호를 나타내기 어려울 것 같습니다. 다른 이름으로 변경해보는 것은 어떨까요?

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Enums.swift
> +enum Operator {
`Enums` 파일명은 용도가 모호한 것 같습니다. 타입별로 파일을 관리하는 것은 어떨까요?

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Queue.swift
> +}
`CalculateItem` 타입에 3가지 요소(`value`, `toggle`, `operator`)를 정의한 이유가 궁금합니다!

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Queue.swift
> +struct Item: CalculateItem, Equatable {
`CalculateItem` 타입의 구현체를 만들어보셨네요.👍
`Item` 타입을 별도의 파일로 관리하는 것은 어떨까요?

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Queue.swift
> +struct CalculateItemQueue<T: CalculateItem> {
파일명을 타입의 이름이 아닌 `Queue` 로 지정하신 이유가 궁금합니다!
`CalculateItemQueue` 타입을 구조체로 정의하신 이유가 궁금합니다!

2023-01-17 14:29 UTC, zdodev commented on Calculator/Calculator/Model/Queue.swift
> +    @discardableResult
`@discardableResult` 을 사용하신 이유가 궁금합니다!

2023-01-17 14:29 UTC, zdodev commented on Calculator/QueueTests/QueueTests.swift
> +    func test_enqueue로_item이_들어갔는지_확인() {
테스트 이름을 잘지어보셨네요.👍

2023-01-18 01:11 UTC, llimental commented on Calculator/Calculator/Model/Enums.swift
> +enum Toggle {
숫자의 부호를 나타내는 의미로 사용되었습니다만, STEP2에서도 사용되지 않는 코드이기에 삭제를 하려합니다.

2023-01-18 01:12 UTC, llimental commented on Calculator/Calculator/Model/Queue.swift
> +}
만들어야 하는 계산기를 만들 때 필요하다고 생각되는 구조로 Item을 만들어서 사용하려 했으나, STEP 2에서는 UML에 맞게끔 코드를 구현하라고 해서 해당 부분을 삭제했습니다.

2023-01-18 01:12 UTC, ohdair commented on Calculator/Calculator/Model/Enums.swift
> +enum Operator {
Toggle은 삭제를 하였고 모호한 Enums에 대한 파일명은 Operator로 변경하였습니다

2023-01-18 01:13 UTC, llimental commented on Calculator/Calculator/Model/Queue.swift
> +struct CalculateItemQueue<T: CalculateItem> {
파일명을 타입명에 맞게 `CalculateItemQueue`로 변경하였습니다.
애플은 [가이드라인](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에서 구조체 사용을 권장하는 조건 중에서 아래의 내용을 충족한다 판단되어 구조체를 사용하였습니다 
    `- 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할 때`
    `- 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없을 때`

2023-01-18 01:14 UTC, llimental commented on Calculator/QueueTests/QueueTests.swift
> +    func test_enqueue로_item이_들어갔는지_확인() {
감사합니다!

2023-01-18 01:14 UTC, ohdair commented on Calculator/Calculator/Model/Queue.swift
> +    @discardableResult
dequeue()를 할 때 반환값을 사용할 수도 있고 오로지 queue의 요소만을 삭제하는 용도로도 사용될 수 있을 거라 판단을 했고 두 개의 용도를 충족을 할 수 있도록 사용하였습니다.
반환값이 존재할 때에 사용하지 않으면 에러를 XCode에서는 에러를 발생시키기에 이 부분을 해결하고자 사용하였습니다.

2023-01-18 01:15 UTC, ohdair commented on Calculator/Calculator/Model/Queue.swift
> +struct Item: CalculateItem, Equatable {
Step 2에서는 Formula로 구현이 되기에 기존 코드는 삭제하였고, 추후 과정에서는 별도로 관리해보도록 하겠습니다.

2023-01-18 01:18 UTC, ohdair commented
이번 STEP1의 리뷰를 받으면서 그리고 STEP2의 요구사항을 받게되면서, 기획자의 의도와는 다르게 임의대로 코드를 추가하게 되면 코드를 수정하는 시간이 더 소요될 수 있다는 것을 알게 되었습니다. 코드 리뷰해주셔서 감사합니다 😊

2023-01-18 13:12 UTC, zdodev approved these changes
안녕하세요. @llimental , @ohdair !

궁금증에 대한 코멘트를 잘 달아주셨습니다.👍
코드에 대한 생각을 잘 표현해주신 점이 좋았습니다!

스텝 1 고생하셨습니다!
다음 스텝도 화이팅입니다!🥳

2023-01-18 13:12 UTC, merged