계산기 [STEP 1] Avery, Miro
tasty-code/ios-calculator pull request #14
Opened 2023-01-17 02:50 UTC by longlivedrgn

> 안녕하세요 븨븨(@YebinKim)~~! 🙌🏻 
계산기 프로젝트를 진행하게 된 Avery, Miro 예요 :) 이번 프로젝트의 리뷰어로 븨븨를 만나서 너무 반가워요.
이번 Step1은 요구사항이 간단하여 비교적 내용이 적었지만 다음 스탭부터는 여쭤보고 싶은 것이 많을 것 같아요..! 이번 프로젝트를 통해 븨븨께 많은 조언을 얻어보고 싶어요. 😁 잘 부탁드려요~! 🙇‍♂️🙇🏻‍♀️
 
## Step 1 요구사항 📌

- 사칙연산 계산을 위한 큐(Queue) 타입(CalculatorItemQueue)과 큐타입 구현을 위한 List 타입을 직접 UML로 표현해요.
    - CalculatorItemQueue를 코드로 구현해요
    - CalculatorItemQueue의 내부구현은 자율로 해요.
    - CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜 (현재는 빈 프로토콜)을 준수해요.
- 프로젝트에 단위 테스트(Unit Test)를 위한 타깃을 추가하고, TDD를 기반으로 수행해요.

## UML 클래스 다이어그램 🖌
<img width="479" alt="스크린샷 2023-01-17 오전 10 15 11" src="https://user-images.githubusercontent.com/85781941/212798536-5ce86617-7cd8-408e-bb8d-7c2add576fe0.png">

## 고민 사항 👀

### 1. Array VS Linked List

저희는 `CalculatorItemQueue`라는 Queue타입을 구현했어요. 해당 타입을 구현을 고민하던 중 저희는 array를 통하여 구현을 할 지, 아니면 linked list를 새롭게 정의하여 큐를 구현할 지 고민했어요.
먼저, 저희가 생각한 linked list의 장점과 단점은 아래와 같아요.
- 중간에 위치한 요소를 삭제하고 삽입하는 데 빨라요.
- 원소를 탐색하는 데에는 느려요.

근데, 요구사항 속 계산기 작동 화면을 참고해보았을 때, 중간에 위치한 요소를 삭제하고 삽입할 일이 없을 거 같아 저희는 array를 선택했어요. 이러한 과정에 대해서 븨븨의 생각이 궁금해요!🧐

### 2. TDD

저희는 이번 프로젝트를 통하여 처음으로 TDD방식을 활용해보았어요. 

테스트를 통하여 아래의 기존 코드는 빈 queue에서 dequeue를 할 시에 error가 나와 런타임 에러가 나오는 것을 확안했어요.

```swift
public mutating func dequeue() -> T {
        return data.removeFirst()
    }
```
그래서 아래의 코드와 같이 빈 Queue인지 확인 후, 빈 Queue에서 dequeue시 nil을 return하도록 코드를 변경해주었어요. 

```swift
public mutating func dequeue() -> T? {
        return isEmpty ? nil : data.removeFirst()
    }
```
처음으로 TDD를 통하여 개발을 하려다보니, 어색하기도 했고 제대로 활용하지 못한거 같아요. 혹시 위와 같은 방식이 올바른 TDD 방식인 지 궁금해요! 그리고, 현업에서는 어떻게 TDD를 활용하고 있는 지 또한 궁금해요!🧐

2023-01-17 12:52 UTC, YebinKim requested changes
에이브리, 미로 안녕하세요~
계산기 프로젝트를 함께 진행하게 된 비비입니다 😄

프로젝트 요구 사항과 고민 사항을 꼼꼼히 적어주셔서 각 커밋을 이해하기 편했어요! 😆👍


리뷰 코멘트 확인 전 아래 내용 확인 부탁드리며, 질문 사항은 밑줄선 아래에서 일괄 답변드리도록 할게요~

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. Array VS Linked List
배열을 선택하기에 충분히 타당한 근거라고 생각합니다! 😄
개인적인 생각으로는 Swift에서는 배열을 사용할 때 배열 버퍼 사이즈를 신경쓰지 않아도 되니 더 선택하기에 부담이 없는 거 같아요.

### 2. TDD
TDD를 제대로 했는가 아닌가에 대해서는 평가하기 어렵지만..😵
Test Coverage 를 봤을 때 실행되지 않은 메서드가 있어서 이 부분은 라인별 코멘트에 남겨뒀어요~
<img width="860" alt="test coverage" src="https://user-images.githubusercontent.com/38066039/212903688-09d11382-5685-4fec-810d-5b3d3ad42201.png">

그리고 저는 TDD를 하기 위해 필요한 것은 꼼꼼한 요구사항 분석과 [ 레드(컴파일 실패, 필요한 테스트 및 타입 껍데기 작성) -> 그린(컴파일 성공, 타입 내부 채우기) -> 리팩토링 ] 절차라고 생각하는데요 🤔
TDD는 프로젝트에 필요한 타입과 로직을 **테스트 통과** 를 기준으로 빠르게 작성할 수 있도록 하는 방법이고, 요구사항을 꼼꼼히 분석해야 레드에 해당하는 테스트를 충분히 작성할 수 있기 때문에 `요구사항 분석` 및 `레드 단계`를 충분히 진행하는 게 필요하다고 생각합니다 ㅎㅎ

---

이번 스텝의 요구 사항은 아래와 같았는데요.
<img width="307" alt="step1" src="https://user-images.githubusercontent.com/38066039/212903635-bf598efd-381c-4863-a600-cd68312ed19b.png">

스텝 요구사항은 충분히 만족했지만 p2 코멘트와 테스트되지 않은 `CalculatorItemQueueTests` 내부 메서드가 있어서 Request Changes 로 요청드렸어요~

코멘트 관련해서 궁금한 점 또는 그 외 프로젝트 진행 중 궁금한 점이 있으면 편히 질문 주세요 🙇🙌

2023-01-17 12:52 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    public init() {}
질문;

생성자와 메서드를 public으로 만든 이유가 무엇일까요??

2023-01-17 12:52 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
p2;

생성자와 메서드는 public 이지만 `CalculatorItemQueue` 타입은 internal 접근제한을 가지고 있어서 모듈 밖에서는 생성이 불가능할 것으로 보여요 🤔
의도된 설계가 아니라면 수정이 필요해보입니다!

2023-01-17 12:52 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
연산 프로퍼티로 작성된 덕분에 문법이 자연스럽게 읽히네요!! 😆👍

2023-01-17 12:52 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
p3;

제네릭 `T` 는 타입 안에서 어떤 역할을 할지 가늠이 안 되는 이름으로 보여요 👀
Swift API Design Guidelines의 [Promote Clear Usage](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage)에 따라 좀 더 의미있는 이름을 사용해보면 어떨까요?

> Name variables, parameters, and associated types according to their roles, rather than their type constraints.

---
한 단계 더 나아가기 🚀;

또한, 현재 `CalculatorItemQueue` 에서는 어떤 타입이든 `T` 로 사용될 수 있어서 아래와 같은 코드도 문제 없이 컴파일이 될 것으로 보이는데요.

```Swift
_ = CalculatorItemQueue<UIViewController>()

struct TempType {}
_ = CalculatorItemQueue<TempType>()
```

큐를 의도에 맞게 사용할 수 있도록 하려면 어떤 제약이 필요하고 또, 제약을 걸어줄 수 있는 방법에는 무엇이 있을지 생각해볼 수 있을까요?

아래 코멘트는 이번 프로젝트가 끝난 후 다음에 생각해봐도 좋습니다!! ☺️

2023-01-17 12:52 UTC, YebinKim commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<Int>!
sut 를 활용하셨군요! 🤩
덕분에 테스트하고자 하는 게 무엇인지 한 눈에 들어옵니다 👍

2023-01-17 12:52 UTC, YebinKim commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(3, dequeuedData)
p3;

3 이라는 숫자를 하드코딩하고 있네요 🤔
이 경우 테스트하고자 하는 숫자가 바뀌면 두 줄을 수정해줘야 하고(40번과 47번을 수정)
프로그래머가 실수하기 쉽게(또한, 유지보수하기 어렵게) 될 것으로 예상돼요 😵

`test_3_4를_enque했을때_총_element숫자가_2개인지()` 메서드와 같이 상수값을 정의해서 사용해보면 어떨까요?

2023-01-17 12:52 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
p2;

이 메서드는 테스트되지 않는 것으로 보이네요! 👀
테스트를 작성하지 않은 이유가 있을까요??

2023-01-18 01:08 UTC, devxsby commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
꼼꼼한 확인 감사합니다 븨비!!! 👍🏻저희가 테스트 커버리지를 미처 확인하지 못했어요..🥲
다음부터는 같은 실수하지 않도록 꼼꼼히 확인해보도록 할게요. 조언 감사해요!!
해당 테스트는 [5d7903f](https://github.com/tasty-code/ios-calculator/pull/14/commits/5d7903f6a9969be2282da6caa01e3a093960e2b5) 커밋에 반영했어요 !! 😊

2023-01-18 01:10 UTC, longlivedrgn commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(3, dequeuedData)
넵! dequeue될 것으로 예상되는 값이라는 의미에서 expectedValue로 상수명을 설정하여 하드코딩을 피했어요!😆
[72d26c3](https://github.com/tasty-code/ios-calculator/pull/14/commits/72d26c304c34bf67539a4f36eb9aa2abaff29dc5) 커밋에 반영했어요! ☺️

2023-01-18 01:10 UTC, devxsby commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
감사해요 🙌🏻

2023-01-18 01:13 UTC, longlivedrgn commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<Int>!
감사합니다! :)

2023-01-18 01:48 UTC, longlivedrgn commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
먼저 답변 감사해요!🌈

처음에는 `CalculatorItemQueue`타입의 프러퍼티와 메소드를 둘 다 **private**으로 설정을 했었어요.
근데, **private**으로 설정을 했을 경우, test 파일에서 접근이 불가능하여 **public**으로 변경을 하였는데,
@testable **import**시 **internal**로만 설정해두어도 test 코드에서 접근이 가능하다는 것을 알게되었어요🥲

앞으로 **private** 메소드와 프로퍼티를 test하는 방법에대해서 더 공부를 해볼 예정이에요! 😀
혹시, 해당 부분에 대해 추가적으로 공부해 볼 키워드에 대해 조언해 주실 수 있으실 까요? 🤔

2023-01-18 01:53 UTC, longlivedrgn commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    public init() {}
[아래 코멘트](https://github.com/tasty-code/ios-calculator/pull/14#discussion_r1073009023)에 해당 내용에대해 답변을 했는데, 확인해주실 수 있으실까요? 🤩

2023-01-18 06:54 UTC, longlivedrgn commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
제네릭 `T`는 queue속의 element의 type을 의미하므로 elementType으로 이름을 변경했어요~!😌
그리고 해당 타입은 Double type만 받을 수 있게(일단, Double만 받게 했어요!)  Double의 extension으로 `CalculateItem`프로토콜을 채택하게 하고,`CalculatorItemQueue` 제네릭 타입 제한으로는 `CalculateItem`프로토콜을 채택했어요.

혹시 븨븨가 말씀해주신 제약을 거는 방법이 위의 방법이 맞을까요? 🤩
위의 사항은 [5562240](https://github.com/tasty-code/ios-calculator/pull/14/commits/5562240cc803395ffc0f183c5ec83914e9b37496) 커밋에 반영했어요! ☺️

2023-01-18 08:17 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
테스트를 위한 접근 제한자 설정이었군요! 변경된 커밋까지 확인했습니다 😆
private 접근 제한자와 test 방법에 대해서는 지금 정리해주신 내용까지만 알아도 충분할 거 같아요!

개인적으로 test 관련해서 추천드리는 공부는 이 영상만 봐도 충분합니다 🤩
https://developer.apple.com/videos/play/wwdc2019/413/

고생 많으셨어요~

2023-01-18 08:23 UTC, YebinKim commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
`제네릭 T는 queue속의 element의 type` 이라는 의미가 와닿았어요! 🤩

다만, `Type` 이라는 명칭은 다소 중복된다는 생각이 드는데요 🤔
Swift API Design Guidelines의 [Promote Clear Usage](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage)에서는 가능한 불필요한 단어의 사용을 지양하고, Type 이라는 말 대신 해당 프로퍼티의 용도를 설명할 수 있는 이름을 사용할 것을 권장하고 있어요.
> Omit needless words. Every word in a name should convey salient information at the use site.

이 부분은 추가로 수정해도 좋고 이대로 넘어가도 좋을 거 같습니다~

---

또한, 제약을 거는 방법으로 **Double의 extension을 활용**하는 것 또한 멋진 방법이라고 생각해요 😆👍
제가 생각한 방향은 [Numeric](https://developer.apple.com/documentation/swift/numeric) protocol 을 활용하는 방향이었는데 현재 구현 또한 괜찮다고 생각해요!

2023-01-18 08:24 UTC, YebinKim approved these changes
미로, 에이브리 안녕하세요~
Step1 수정까지 고생 많으셨습니다!

질문에 대한 추가 코멘트가 있으니 확인 부탁드리고, 이대로 머지해도 괜찮다면 바로 머지 진행하도록 할게요 😄

2023-01-18 08:38 UTC, merged