계산기 [Step 1] iyeah, Jenna
tasty-code/ios-calculator pull request #15
Opened 2023-01-17 04:18 UTC by ueunli

안녕하세요 Jake !! @jryoun1
이번 계산기 프로젝트를 함께 진행하게 된 iyeah & Jenna입니다 🌱
STEP 1의 구현 사항이 간단해서 구현한 코드가 많지 않지만,
프로젝트에 첫 Uint Test를 적용해보았어요 👍🏻
부족하겠지만 프로젝트를 완수하기 위해 열심히 노력할게요!
리뷰 잘 부탁드려요 😇 
　

## :heavy_check_mark: 구현 사항
### :small_blue_diamond:Unit Test
- 프로젝트에 단위테스트를 위한 타깃을 추가

### :small_blue_diamond:CalculatorItemQueue
- `CalculatorItemQueue` 의 내부규현은 자율
- `CalculatorItemQueue` 에서 다루는 요소는 `CalculatorItem` 프로토콜을 준수
   - `calculateItem` 프로토콜은 빈 프로토콜임

### :small_blue_diamond:UML
![uml-image](https://cdn.discordapp.com/attachments/1064346306337853561/1064731728876408983/2023-01-17_11.12.47.png)

## :heavy_check_mark: 고민 사항
연산Queue 또는 그 내부의 List를 어떤 타입으로 어떻게 구현할지 고민이 많았어요.
> ### 요소 타입
- 아직 전체적인 앱의 구조나 VC구현을 명확하지 않아 큐나 리스트에 연산자나 피연산자를 String인 채로 가져올지, VC에서 Double이나 Character 또는 커스텀타입(enum 등)으로 변환해서 가져오게 될지 알 수 없었어요.
- 일단 뷰에 주어진 요소의 타입이 UIButton인 점만 감안하여 String(text속성)으로 가져올 것임을 전제로 작성하였고,
- 담을 요소의 타입을 통일했으므로 제네릭은 적용하지 않았습니다.

> ### 연산큐 내부 List의 타입
큐 구현방법 중 '더블스택'을 응용하여,
`=`입력 전까지는 초반요소들의 dequeue가 아니라 '직전요소삭제'만 이루어진다는 점에서 오히려 스택스럽다고 생각, 아래와 같은 방법을 생각했어요.
1. 스택 1: '직전입력요소'(=삭제될 수 있는 임시입력값) 저장하는 배열
2. 스택 2: '입력확정요소'들을 순서대로 저장하는 배열

위와 같이 ""`2개의 배열 프로퍼티`를 갖는 List로부터 최종 계산식을 반전된 형태로 받아와 dequeue용 배열로 쓰는 연산큐", 
즉 입력중엔 스택처럼, 입력후엔 큐로서 다루는 방식을 고려하였는데, 괜찮은 관점에서 접근한 것인지에 대해 제이크의 의견을 듣고 싶습니다!
　
　

2023-01-18 13:49 UTC, jryoun1 requested changes
iyeah, Jenna 고생하셨습니다! 

코드를 가독성 있게 작성해주셔서 코드를 잘 읽을 수 있었습니다 💯👏
UML도 잘 작성해주셨네요 👍🏻

현재 구현한 사항들에 대해서 왜 그렇게 선택하고 구현하셨는지 남겨주셔서 좋았습니다. 
넵 괜찮은 것 접근방식인 것 같네요! 
다만 여유가 있으시다면, 다른분들이 구현하시는 방법들도 이야기 해보고 확인해보면 좋을 것 같네요 ㅎㅎ 

그럼 몇 가지 코멘트 남겨두었으니 확인부탁드립니다. 🙏🏻

2023-01-18 13:49 UTC, jryoun1 commented on .gitignore
> +
gitignore에 필요한 부분들을 추가해주셨네요 👏

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorError.swift
> +enum CalculatorError: Error {
Error타입도 정의해주셨군요 👍🏻

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var itemArray = [String]()
private(set) 을 사용해 접근제어를 해주셨네요 💯

다만 변수명은 Array라고 직접 붙이기 보다는 `items` 라고 하는 것이 좀 더 일반적입니다 🙏🏻

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
struct 타입으로 구현하신 이유가 궁금합니다 🙋‍♂️ (단순 질문)

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws {
계산기 queue에서 dequeue를 했다면 해당 값으로 연산을 해야할 것 같은데, 반환되는 값은 없어도 될까요? 🙋‍♂️

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +final class CalculatorTests: XCTestCase {
final 키워드도 붙여주셨군요 👏 
어떤 이유 때문에 붙었을까요? 🙋‍♂️

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    override func setUp() {
setUp과 setUpWithError가 있었을텐데 두 함수의 차이는 무엇일까요? 
tearDown, tearDownWithError도 동일합니다!

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        }()
result로 작성하는 것도 좋지만, test를 작성할 때 포맷은 given - when - then도 있으니 한 번 찾아보셔도 좋을 것 같네요 🙏🏻

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertFalse(result)
XCTAssert를 필요에 따라서 잘 작성하고 계시군요 👏💯

2023-01-18 13:49 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertThrowsError(try sut.dequeue())
크~ 비어있을때 삭제까지 테스트 좋네요 👏

2023-01-19 01:00 UTC, ueunli commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var itemArray = [String]()
네이밍 추천 감사해요! 수정하였습니다!
 
> 해당 커밋 링크 (https://github.com/tasty-code/ios-calculator/pull/15/commits/c8017a1caecb385813dc4bd0918c34c52b08c9fc)

2023-01-19 01:00 UTC, iYeahh commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws {
앗..! 반환되는 값이 필요해서 리턴형이 있는 함수로 변경하였습니다 🙂

> 해당 커밋 링크 (https://github.com/tasty-code/ios-calculator/pull/15/commits/c8017a1caecb385813dc4bd0918c34c52b08c9fc)

2023-01-19 01:26 UTC, ueunli commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() throws {
사실 테스트를 위해 소스코드를 변경해야 될 것 같아 고민한 부분이 2군데 있었어요
1. `itemArray`(`items`)를 private → private(set)으로 (변경o)
2. 이번에 `dequeue()`가 반환값을 가지도록 수정하면서, 반환값을 사용하지 않는 부분(테스트파일 line54)에 경고가 뜨지 않도록 어트리뷰트 키워드(`@discardableResult`)를 붙여야 하는가 (변경x)

`private(set)`, `@discardableResult` 모두 유닛테스트를 위해 설정된 부분인데, 후자의 경우 테스트코드 말고는 앞으로도 필요할 일이 없을 것 같아(= 항상 반환형을 사용할 것 같아) 적용하지 않았어요.
다음 스텝들 진행하면서 계속 고민해 볼게요 🙆🏻‍♀️

2023-01-19 01:28 UTC, iYeahh commented on Calculator/CalculatorTests/CalculatorTests.swift
> +final class CalculatorTests: XCTestCase {
해당 클래스에서 하위 클래스로의 상속 및 재정의가 필요하지 않은 경우 `final` 키워드를 추가하여 상속을 방지하도록 하고,
`final` 키워드를 사용하면 컴파일 시점에 어떤 메서드와 프로퍼티를 호출할지 결정하므로 성능상의 이점이 있어 사용하였어요!

2023-01-19 02:25 UTC, ueunli commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        }()
given-when 사이의 경계를 뚜렷하게 구분하기 어려워 result로 뭉뚱그렸던 것 같아요..!
짚어주신 덕분에 given-when-then 각각의 의미와 예시를 더 찾아볼 수 있었어요!

같이 공부한 결과, 
- 일반적으로 given, when, then에 해당하는 코드 사이사이에 개행을 해준다는 점
- given부분에서 먼저 변수를 선언해주고, when에서 그 변수를 사용해준다는 것

2가지를 알게 되었고, 이 커밋 https://github.com/tasty-code/ios-calculator/pull/15/commits/98c5009097be856361fb28c6d3f449320cca8cf0 에서 수정하여 반영했어요🌱

2023-01-19 02:28 UTC, ueunli commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        }()
몇몇 테스트함수는 어떻게 패턴에 맞춰야 할지 헷갈리는 부분이 있었어요
- `test_빈배열이면_true이다()` ― given에 해당하는 부분을 찾기 어려웠어요
- `test_배열에_추가한_순서대로_삭제된다()` ― when, then이 do-catch문 안에 묶여 있어 개행처리를 어떻게 해야할지 모르겠어요

2023-01-19 02:29 UTC, iyeahh commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
상속이 필요하지 않고, 주소값을 전달하여 여러 곳에서 사용할 경우도 없다고 생각했어요.
꼭 class 타입으로 구현해야 하는 경우가 아니라면 연산이 빠르고 관리가 쉬운 Stack에 저장되고, Static Dispatch인 값타입(struct)으로 구현하는 것이 성능면에서 유리하다고 판단하였습니다 🙋🏻‍♀️

2023-01-19 04:13 UTC, jryoun1 commented
고생하셨습니다 👏
답변들도 잘 남겨주셨고, 수정도 잘 해주셔서 이번 스텝은 여기서 머지해도 될 것 같습니다 👍🏻
step2도 화이팅입니다!

2023-01-19 04:13 UTC, merged

2023-01-19 06:38 UTC, ueunli commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    override func setUp() {
setUp와 tearDown은 테스트를 위해 인스턴스를 세팅(새로 생성 및 해제)해주는 메서드, 
setUpWithError와 tearDownWithError는 위와 같지만 에러핸들링을 할 수 있는 메서드입니다.
현재 XCTestCase의 기본값은 후자로 되어있지만, 
sut을 생성·소멸할 때 에러가 발생할 가능성이 있을 만큼 복잡한 프로젝트는 아니므로 setUp, tearDown을 사용했어요 !!