Calculator [STEP1] Mason, Blue
tasty-code/ios-calculator pull request #17
Opened 2023-01-17 05:32 UTC by qwerty3345

안녕하세요 라자냐! @wonhee009

계산기 프로젝트를 진행하게 된 팀 🔮MABLE🔮 의 Mason, Blue 입니다 😊
STEP1 의 내용이 많지 않았지만, 익숙치 않은 TDD 를 적용 해서 진행 해 보았습니다!
이번 프로젝트를 통해 많은 조언 해 주시면 스펀지처럼 흡수 해 쑥쑥 성장하겠습니다 🧽🫧
리뷰 잘 부탁드립니다! 감사합니다 💙

# ✅ 요구사항 & 체크리스트

- [x]  UML 작성 → 큐(Queue) 타입과 큐타입 구현을 위한 List 타입
- `CalculatorItemQueue` 코드로 구현
    - [x]  `CalculatorItemQueue`에서 다루는 요소는 `CalculateItem` 프로토콜을 준수
        - [x]  비어있는 `CalculateItem` 프로토콜 생성
    - [x]  **(선택)** `CalculatorItemQueue`의 내부에서 사용하는 List 형식의 자료구조를 `LinkedList`로 구현
        - [x]  `LinkedList` 구현을 위한 `Node` 클래스 생성

# ✏️ 학습 키워드

- TDD, Unit Test
- UML
- 자료구조 (Queue, Linked List)
    - 시간 복잡도
- Generics
- defer 키워드 **(추가 학습 필요)**

# 💬 UML

![계산기_프로그램_클래스_다이어그램](https://user-images.githubusercontent.com/59835351/212817217-4bcf6fa2-1907-436e-ac4e-a429951b4985.jpg)

# **⁉️ 고민과 해결**

## Queue 구현 시 Array vs Linked List

먼저 Queue 내부의 요소를 `Array`로 구현하는 것을 고려하였습니다.
하지만, **dequeue**를 구현하는 경우 `array.removeFirst`를 활용하면
배열 특성상 삭제된 요소로 인해 남아있는 **모든 요소들의 index를 변경**해줘야 하기에 **시간복잡도**가 $O(n)$이 되는 것으로 보입니다.
어떻게 하면 시간복잡도를 $O(1)$으로 만들 수 있을지에 대해 고민하였습니다.

### ⏳ Queue 기능 구현 시 시간 복잡도

`dequeue` _ 가장 앞의 요소를 삭제

- Array 로 구현:  $O(n)$
- Linked List 구현: $O(1)$
    
    > head 만 삭제하고, 해당 다음 노드를 head 로 지정해주면 됩니다.
    > 

`enqueue` _ 가장 뒤로 요소를 삽입

- Array 로 구현: $O(1)$, 최악의 경우 $O(n)$
    - Array 의 append 메서드를 호출하는데, 
    배열은 저장공간의 사이즈가 고정되어 있기에, 해당 배열의 최대 사이즈를 넘어서 `append()` 를 실행하면 저장 공간을 realocate하는 작업이 발생하여 최악의 경우 시간복잡도가 O(n)이 됩니다.
- Linked List 구현: $O(1)$
    - reallocate 가 발생하지 않습니다.

### **🤔 그렇다면 Linked List 방식의 단점은??**

- LinkedList 로 구현할 경우, 각 Node가 다음 Node의 주소값을 참조해야 하므로 각 노드를 class 로 Heap 영역에 저장해야 합니다.
    - Heap 에 저장될 필요가 없는 데이터들도 Node class 로 Wrapping 해야 합니다.
- Linked List 방식의 전체적인 시간복잡도는 줄어들 수 있겠지만… 공간 복잡도는 훨씬 커지지 않을까 라는 생각이 들었습니다?
- 이에, 어느 부분을 최적화 하는 것을 우선시할 것인가에 대한 **”선택의 문제”** 라고 판단을 내렸습니다.
    
    > 이번 계산기 프로그램 같은 경우는 Array 로 구현해도 큰 차이가 발생하지 않을 것이라 판단되지만, 
    학습의 목적으로 Linked List 로 구현 해 보았습니다.
    > 

🤔❓ 저희가 학습한 두 자료구조의 차이가 적절한지와, 라자냐라면 어떤 방식을 사용하실지에 대해 의견이 궁금합니다!

## TDD

이번 STEP1 에서 Queue, Linked List 타입을 구현할 때 TDD 방식으로 진행하였습니다.
실패 케이스를 한 개 해결한 후 다음 케이스를 작성하였는데, 
앞선 실패케이스를 해결하면서 [새로 작성한 테스트 케이스도 success가 되는 경우](https://github.com/qwerty3345/ios-calculator/commit/226d732a502e8cd2ffffde01bd1f435a922e88c2)가 발생하였습니다.

```swift
// LinkedList.swift
func test_여러요소를_append했을때_마지막으로_넣은_요소가_tail이다() {
    // given
    let inputs = [1, 2, 3, 4, 5]

    // when
    inputs.forEach {
        sut.append($0)
    }
    guard let tailValue = sut.tail?.value as? Int else {
        return XCTFail()
    }

    // then
    XCTAssertEqual(inputs.last, tailValue)
}
```

TDD는 실패 케이스 작성 → 테스트 통과 → 리팩토링의 순환 과정을 거쳐야 한다고 배웠는데, 
🤔❓ 위처럼 테스트 진행 전에 성공하는 케이스가 발생하게 되면… 바로 다음의 실패하는 케이스를 작성하면 되는걸까요?
 

🤔❓ 또한, 저희가 작성한 테스트 코드의 형식이 적절한지도 궁금합니다!

2023-01-17 12:55 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겼으니 확인 부탁드립니다.

- 네 알맞게 학습하신거 같습니다. 저라면 Array, LinkedList 구현에 대해 명세로 정해진게 없다면 Array로 구현했을거 같습니다.
- "테스트 진행 전에 성공하는 케이스"를 이해하지 못했습니다. 실패하는 케이스를 작성하는데 테스트 진행 전에 어떻게 성공하는거죠...?
- 넵 좋습니다.

2023-01-17 12:55 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
struct의 이름은 `-Queue`이니 Queue에서 사용하는 네이밍으로 바꿔주는건 어떨까요?

2023-01-17 12:55 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculateItem.swift
> +}
아무런 기능이 없는 프로토콜 같습니다.
`Double`만 채택하고 있고요. 필요한 프로토콜인가요?

2023-01-18 00:42 UTC, qwerty3345 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
front, rear 로 변경 하였습니다 :)

2023-01-18 00:42 UTC, bomyuniverse commented on Calculator/Calculator/Model/CalculateItem.swift
> +}
STEP 1 요구사항 내에 `CalculateItem 프로토콜은 빈 프로토콜입니다` 라고 명시가 되어있었고, 해당 프로토콜에 추가적인 요구사항이 없어서 빈 프로토콜로 생성해 두었습니다.
추후 다른 STEP 진행 시 필요할 것으로 생각됩니다!

2023-01-18 00:56 UTC, bomyuniverse commented
> * "테스트 진행 전에 성공하는 케이스"를 이해하지 못했습니다. 실패하는 케이스를 작성하는데 테스트 진행 전에 어떻게 성공하는거죠...?

리뷰 감사해요 라자냐!
위에 언급한 부분은 저희가 말을 잘 못한 것 같아서 다시 설명드려요!

TDD 진행 시 저희는 해당 메서드가 수행해야 하는 작업에 대한 제약조건들을 test case로 나열하고, 순차적으로 해당 case를 test 하는 방향으로 진행하였습니다.
`무조건 실패해야하는 케이스`를 고려하지 않고 순차적으로 테스트를 진행하다보니, 실패 -> 수정의 과정을 거쳐야 하는데 첫 시도부터 성공하는 테스트 케이스가 발생하였습니다.

저희가 한 방법대로 미리 테스트 케이스에 대한 설계를 마친 후 테스트를 진행해도 되는지,
아니면 한 가지 테스트 케이스 통과 후 그 상태에서 실패해야 하는 케이스를 생각하고 테스트를 진행해야 하는지 궁금합니다!

저희가 프로젝트에 TDD를 적용하는 것이 처음이라 많이 미흡한 점 양해 부탁드립니다! 😢

2023-01-18 01:26 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculateItem.swift
> +}
아핫! 네넵 클로즈하겠습니다~

2023-01-18 01:54 UTC, wonhee009 commented
아핫 네넵 이해했습니다. 정석적인 TDD 방식이라면 한가지에 대한 테스트 코드를 작성하고 테스트를 진행하고 수정하는거로 알고 있습니다. 지금은 연습하는 과정이니 정석대로 연습해 나가는게 좋지 않을까 싶습니다.

2023-01-18 01:54 UTC, wonhee009 approved these changes
수고하셨습니다~

2023-01-18 01:54 UTC, merged