계산기 [STEP 1] D.O, Sunny
tasty-code/ios-calculator pull request #19
Opened 2023-01-18 04:02 UTC by SunnnySong

# Step1 PR

안녕하세요 콘😄 이번 계산기 프로젝트를 하게 된 D.O와 Sunny입니다☺️

이번 Step은 구현해야 할 요구사항은 적었지만 새로운 자료형과 자료구조를 사용해보느라 다른 프로젝트보다 더 어려웠던 Step1이었던 것 같아요🤯 그래도 프로젝트를 통해 최대한 많은 지식을 얻고자 자료형에 대해 열심히 공부하고 또 프로젝트에 적용해보았어요!

PR 제일 마지막 부분에는 고민사항이 들어가있어요. 이 부분에 대해 콘의 개인적인 생각이나 알려주고 싶은 정보들을 적어주신다면 열심히 공부하겠습니다😀

-   [X] UML 작성
    -   [X] 사칙연산 계산을 위한 Queue타입 CalculatorItemQueue 구현
    -   [X] Queue타입 구현을 위한 List타입 구현
-   [X] CalculatorItemQueue 코드 구현
    -   [X] CalculatorItem 프로토콜 준수 (빈 프로토콜)
    -   [X] CalculatorItemQueue 내부 List 형식 자료구조 직접 구현(선택)

### UML
![image](https://user-images.githubusercontent.com/85678496/213080043-0e9f0cf6-57f0-419f-b72c-93911a57f0a8.png)

### 구현 세부 사항 및 고민

    ❗ CalculatorItemQueue 의 싱글톤 구현

CalculatorItemQueue를 app 내에서 유일한 객체로 생성하고 사용하기 위해 싱글톤으로 구현했어요. 하지만 더 깊이 공부를 하다보니 싱글톤은 치명적인 단점 때문에 잘 사용하지 않는다는 글을 발견했어요.

-   싱글톤을 사용하는 곳과 싱글톤 class 사이에 의존성이 커져 결합도가 높아진다.
-   app 내 모든 곳에서 싱글톤에 접근해 데이터를 공유할 수 있기 때문에 객체지향 프로그래밍에서는 지양하는 패턴이다.

이러한 싱글톤의 단점 때문에 실제 실무에서는 잘 사용하지 않고 ‘의존성 주입’과 같은 방식으로 대체한다고 공부했는데 저희가 공부한 내용이 맞나요?🤔

     ❌ TDD 기반 코드 구현

이번 Step1의 요구사항에 보면 “Step 1은 TDD를 기반으로 수행합니다.” 라고 적혀있어요. 하지만 저희는 Queue와 Linked List를 공부하는데 시간을 많이 소모했고 결국 이번 Step에서는 TDD 기반 구현을 하지 못했어요😢 다음 Step에서는 Unit Test를 활용하여 코드를 작성해보도록 노력하겠습니다!

     ❗ Queue 내부 List 형식 자료구조 : ArrayList vs LinkedList

CalculatorItemQueue 내부 List 형식 자료구조를 직접 구현해도 된다는 요구사항을 보고 저희는 고민을 많이 했어요. ArrayList를 사용할지, LinkedList를 사용할지 치열한 고민 끝에 아래와 같은 이유로 LinkedList를 사용하기로 결정했어요!

-   정적 vs 동적 자료구조
	- Array는 정적인 자료구조로, 생성하는 순간 특정 양의 메모리가 정해져있어요. 만약 정해진 메모리를 초과하여 elements를 저장하려 한다면 더 큰 양의 Array 메모리가 재생성되어 elements 복사가 일어나요. 
	- 반면 LinkedList는 동적인 자료구조로, 저장하려는 node의 크키가 늘어나도 List추가가 자유로워요.
-   데이터 추가/삭제의 시간복잡도
	- Array는 데이터의 접근/탐색에 있어 시간복잡도가 낮고, Linked List는 데이터의 추가/삭제에 있어 시간복잡도가 낮아요. 이번 프로젝트에서는 Queue 자료구조를 사용하기 때문에 Queue의 tail에서는 데이터의 추가가 일어나고 head에서는 데이터의 삭제가 일어나요. 
	- Queue의 중간에서 데이터의 추가/삭제가 일어나지 않기 때문에 Linked List를 사용하는 것이 시간복잡도 측면에서 유리해요!
-   이번 프로젝트에서는 사칙연산과 숫자만 List에 저장하는 방식이기 때문에 ArrayList를 사용한다해서 유의미한 동작 시간 차이가 날 것이라 생각하지 않았어요. 하지만 Array는 지금까지 많이 사용해보았기 때문에 공부 차원에서 LinkedList를 선택한 이유도 있어요👍

2023-01-18 13:25 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 스탭 특성상 간단한 코멘트만 남겨놓았어요! 

## 구현 세부 사항 및 고민

> ❗ CalculatorItemQueue 의 싱글톤 구현

싱글톤의 장단점에 앞서 두분이 `CalculatorItemQueue를 app 내에서 유일한 객체로 생성하고 사용하기 위해` 라고 결정한 이유가 궁금해요. 

싱글톤의 장단점은 이해하고 계신바가 맞아요. 다만 싱글톤으로 구현되어야 하는 경우도 당연히 있구요. 이 경우 어떤걸 유의해서 작성해야 하는지에 대해 염두를 해두시고 작성하셔야해요.

이에 대해서는 천천히 학습해보시면 좋을 것 같아요. 먼저 한 가지만 생각해본다면 앱 전역에서 쉽게 접근할 수 있기 때문에 데이터 무결성 이슈가 있을 수 있어요. 이 부분에 대해서도 유의해서 작성해주셔야 해요. 

근데 이런걸 떠나서 왜 그 객체는 싱글톤 객체여야 하는지에 대해 명확한 이유가 있어야 해요! 이 부분에 대해 고민해보시면 좋을 것 같아요.

2023-01-18 13:25 UTC, protocorn93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue = LinkedList.shared
1. 싱글톤을 사용해주셨는데, `LinkedList`를 싱글톤으로 사용해야할만한 이유가 딱히 없어보이는데, 그렇게 결정하신 이유가 궁금해요!
2. `var`로 선언될 필요는 없어보이는데, 그렇게 선언한 이유가 궁금하네요! 
3. `enqeue`, `dequeue` 인터페이스가 존재하기 때문에 `private`을 붙여주는게 좋지 않을까요? (UML 상으로도 `-`붙어있네요)

2023-01-18 13:25 UTC, protocorn93 commented on Calculator/Calculator/ItemNode.swift
> +    var next: ItemNode?
`data`는 `let`으로 선언되어야 하지 않을까요?

2023-01-18 13:25 UTC, protocorn93 commented on Calculator/Calculator/ItemNode.swift
> +    var number: Double
여기도 역시 `let`으로 선언될 필요가 있지 않을까 싶네요

2023-01-18 13:25 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    private var head: ItemNode?
저는 보통 `LinkedList`를 구현하면 `tail`이라는 녀석을 하나 더 두고 구현하곤해요. 그러면 `append`나 `remove`가 좀 더 수월할거에요. 다양한 방법으로 구현해보는것도 좋은 경험일 것 같아요!

2023-01-18 13:25 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +        }
`guard`문을 맨 위로 올려 `early exit` 되도록 하는게 좋지 않을까요? 
(사실 여기서 early exit 된다고 큰 성능상 차이는 없어요. 다만 early exit이 가능한 경우라면 불필요한 연산없이 해주는게 좋아요!)

2023-01-19 01:32 UTC, doshkor commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue = LinkedList.shared
1. 사용자가 연산을 입력 할 때마다 순차적으로 큐에 담아서 사용하려고 했어요! 또한 연산자와 피연산자를 struct 에 담아 사용하려고 의도하였기 때문에 큐를 하나만 사용하려고 했어요. ( 현재 STEP2 에서 공개된 내용은 큐가 2개(연산자,피연산자)여서 싱글톤을 사용할 이유가 없어져 변경하려고해요!)
2. `let` 이 좋다고 생각해요!
3. `private` 이 좋다고 생각해요!

2023-01-19 01:33 UTC, doshkor commented on Calculator/Calculator/ItemNode.swift
> +    var next: ItemNode?
격하게 동의해요! 😭

2023-01-19 01:33 UTC, doshkor commented on Calculator/Calculator/ItemNode.swift
> +    var number: Double
여기도 격하게 동의해요! 😭😭

2023-01-19 02:05 UTC, doshkor commented on Calculator/Calculator/LinkedList.swift
> +        }
간과하고 있던 부분인데.. 다시 한 번 생각하게 됬어요! 감사합니다👍

2023-01-19 02:07 UTC, SunnnySong commented on Calculator/Calculator/LinkedList.swift
> +        }
early exit에 대해 생각하면서 코드를 작성하는 습관을 들일게요!☺️

2023-01-19 02:07 UTC, doshkor commented on Calculator/Calculator/LinkedList.swift
> +    private var head: ItemNode?
콘의 리뷰를 받고 `tail` 속성을 추가하고, 이에 따라 `append` `remove` 를 수정해 보았습니다.!

2023-01-19 02:15 UTC, protocorn93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue = LinkedList.shared
1번은 다음 스탭과 무관하게 싱글톤 객체로 구현될 이유로는 부족해보여요! 이건 프로젝트와 무관하게 추후에 학습을 해보시면 좋을 것 같아요

2023-01-19 02:18 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    private var head: ItemNode?
수고하셨습니다! 원할한 PR 커뮤니케이션을 위해서 수정되었다는 코멘트에는 커밋 링크를 함께 첨부해주시면 좋을 것 같아요!

2023-01-19 04:06 UTC, merged