[Step1] 재근, 도도
tasty-code/ios-calculator pull request #2
Opened 2022-09-06 05:31 UTC by wormsJJG

# 수행한 내용
- 프로젝트에 단위테스트 타깃 추가
- Queue타입 구현
- CalculatorItem 프로토콜 생성
- 계산함수 구현
<img width="285" alt="스크린샷 2022-09-06 오후 2 31 23" src="https://user-images.githubusercontent.com/81068345/188554290-bbccdc08-fd12-42f7-926a-13bc5cefe742.png">

2022-09-06 07:53 UTC, jaemuYeo requested changes
Queue타입에 필요한 부분들을 잘 구현해주었네요!
List를 활용한 Queue타입과 지금처럼 구현한 것과 어떤 차이점이 있을까요?
시간 복잡도와 각각의 이점들을 조사해보면 좋을 것같아요~

현재 테스트파일만 만들고 테스트는 진행해보지 않았네요!!
만들어놓은 큐타입이 잘 작동하는지 Unit Test를 진행해보면 좋을 것같아요!
`given when then  패턴`에 대해 조사해보고 활용해보세요 😀💪

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
제네릭 타입을 활용할때 T를 통해 명시해도 되지만
`class CalculatorItemQueue<Element>` 처럼 특정한 네이밍을 주어도 좋답니다 😀
수정하지 않아도 될 부분이니 참고만해주세요!

이 타입은 왜 클래스로 선언되었나요??🤔

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
프로퍼티와 메서드를 public으로 준 이유가 무엇인가요?

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        queue = []
removeAll이란 메서드를 활용해보세요!

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public func clearLast() {
clearLast라는 네이밍보다 removeLast가 어울릴거같아요 ㅎㅎ

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: String {
이 타입은 다음 스텝에 참고할게요!

2022-09-06 07:53 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +class CalculatorTests: XCTestCase {
파일명과 타입명을 `테스트할 객체이름 + Tests`로 해주면 좋아요! 😉

2022-09-07 01:32 UTC, dddowon commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: String {
넵!

2022-09-08 00:50 UTC, wormsJJG commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
object c 상호 운용성을 원하지 않기 때문에 그냥 struct으로 해주면 바꾸었습니다.

2022-09-08 00:52 UTC, wormsJJG commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
오버라이딩을 못하게 할려는 의도입니다.

2022-09-08 00:52 UTC, wormsJJG commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        queue = []
넵

2022-09-08 00:52 UTC, wormsJJG commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public func clearLast() {
넵

2022-09-08 00:52 UTC, wormsJJG commented on Calculator/CalculatorTests/CalculatorTests.swift
> +class CalculatorTests: XCTestCase {
넵

2022-09-08 02:02 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
이럴 경우 fanal class를 사용해도 좋을 것같아요

2022-09-08 02:04 UTC, wormsJJG commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
넵 final에 대해 공부해보겠습니다.

2022-09-08 02:12 UTC, jaemuYeo reviewed
재근 도도 고생하셨어요!
이번 스텝은 머지진행하겠습니다~
단 코멘트에 남겨놓은 부분을 꼭 확인하고 수정이 필요한 부분은 반영해보세요 😀
다음 스텝으로 넘어가기 전 [참고자료](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift/v4.0/chapters/8-queues)를 보며 큐타입에 대해 조금 더 이해하고
넘어가주길 바라요! 다음 스텝에서 만나요 ~~

2022-09-08 02:12 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
지난번 오버라이딩을 막기위해 public으로 했다고 했는데
구조체에서는 어떤가요?

2022-09-08 02:12 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func dequeue() -> T {
dequeue의 경우 큐의 특징인 선입선출에 따라 배열의 제일 앞에가 빠져나오게 됩니다
단 배열은 비어있을 수도 아닐수도 있어요
다시한번 고민해볼까요?

2022-09-08 02:12 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func clearAll() {
clear라는 네이밍만으로도 충분히 표현될거같아요!

2022-09-08 02:12 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에_수가_추가되는지() {
~~ 되는지의 네이밍보다는
given when then 패턴에 맞게
`test_10을큐에넣었을때_큐의요소는_비어있지않다` 이런식으로 ~다 로 끝내면 좋아요!
다음번에 참고해서 진행해보세요 💪

2022-09-08 02:12 UTC, merged

2022-09-08 02:34 UTC, dddowon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에_수가_추가되는지() {
넵

2022-09-08 02:34 UTC, dddowon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func clearAll() {
넵