Calculator [STEP 2] Joo, Lust3r
tasty-code/ios-calculator pull request #21
Opened 2023-01-19 08:19 UTC by llimental

# Calculator [STEP 2] Joo, Lust3r
안녕하세요! 소대(@zdodev)! 이번 Calculator 프로젝트를 진행하게 된 Joo, Lust3r 입니다!
UML 틀에 맞춰 요소를 갖추고 각각의 property와 method에 들어갈 내용을 작성해보았습니다.

"=" 버튼을 눌러야 연산이 진행 되는 것이기에 입력된 모든 숫자와 연산자를 하나의 input String으로 생각하고 과정을 진행하게 되었습니다.
감사합니다! 🙇🏼‍♂️

![188132535-8bc81913-7863-4877-88f9-0f8e811a52bd](https://user-images.githubusercontent.com/45708630/213386825-29d5bd14-4f73-49e0-9862-4d5939af10cb.jpeg)
### UML의 이해
- `Operator`는 연산자의 요소이고 연산자에 맞게 동작해요
- `ExpressionParser`는 입력받은 문자열을 순서에 맞게 연산자와 비연산자를 분리하여 `Formula`생성해요
- `Formula`는 연산자로 이루어진 operators Queue와 Double로 이루어진 operands Queue를 계산해요

## 🧑🏼‍💻 작업 목록

### STEP 2 : [ 스크럼 ](https://www.notion.so/tastycode/1-19-05ce95eec637492593c2ff98c2f6b3b1)

- [ ] 아래 제시한 UML대로 연산과 관련한 타입을 구현
    - [x] UML에 표기한 사항은 모두 구현
- [x] 변수보다는 상수, 반복문 조건문보다는 고차함수 활용
- [ ] 희망시 TDD 적극수행
    - [x] Unit Test 진행

## 💭 학습 키워드

- generic
- enum
- type methods(static)
- map
- compactMap

## 🤔 고민과 해결

- 입력된 내용을 어떻게 끊어야할 지 고민하다 전체 입력된 내용을 가지고 숫자와 연산자를 각각의 배열로 분리하는 방법을 선택하였습니다.
(`componentsByOperators()`, `extractOperators()` 메서드 사용)
- 분리한 [Double], [Operator] 배열을 Queue에 넣기 위한 방법을 고민하다 `Generic`을 통해 어떤 유형의 배열을 받더라도 `enqueue` 작업을 진행하고 `CalculateItemQueue`를 반환할 수 있게 하였습니다.

## 🙋🏻 질문 거리
- UML에서 나와있는 `String.split(with target: Character)`를 사용하여 코드를 구현하기에 어려움이 있어 일단 `func components(separatedBy separator: CharacterSet)`를 사용하여 진행을 해보았습니다.
- Queue의 property를 변수로 설정을 했으나, `private`라는 키워드로 은닉화하려고 합니다. 이렇게 되면 테스트에서는 property에 접근을 할 수가 없기에 `priavte(get)`을 사용해야 하는지 혹은 테스트의 검증이 끝났다고 판단했으면 테스트 파일을 삭제해도 되는 건지 궁금합니다.
- 문자열로 변경하는 코드인데, 둘 중 어느 게 더 나은 건지 궁금합니다
- ```Swift
  String(Operator.allCases.map { $0.rawValue })

  Operator.allCases.map { "\($0.rawValue)" }).joined()
  ```
  
## STEP3 에서 고민해야 되는 부분

- 계산의 처음 숫자의 연산자는 default는 `.add` 이다
(macOS 기본 계산기에서도 숫자 버튼 누르기 전에 연산자를 변경 가능)
- 계산기의 순서는 아래와 같다
    1. 연산자를 입력 (첫 숫자 입력의 연산자는 `.add`)
    2. 숫자를 입력
    3. 1 ~ 2번의 행동을 반복하게 된다
- `+ / -`는 String으로 입력받는 형태(`sign`)에서 기호로 받는다
    
    ```swift
    // ➕, ➖: 이모지로 positive와 negative를 판단하도록 분리
    "+15➕*10➕-17➖"
    ```
    
- parse 부분에서 `sign`을 구분짓고 새로운 Queue를 만들어야 한다
- `.`의 입력을 받았다면 1번만 받도록 enum으로?? 관리한다
- `sign`과 `.` 을 계산기의 순서에서 새로운 연산자를 받을 때마다 초기화를 한다
(`.`은 unused, used로 구분 / `sign`은  positive, negative로 구분)
- 그 외에 예외 사항은 STEP3에서 입력받을 때 처리를 해야한다 판단한다

2023-01-24 14:56 UTC, zdodev requested changes
안녕하세요. @llimental , @ohdair !

Step2 구현 잘 진행해주셨습니다!

남겨주신 질문에 대한 제 생각을 말씀드리면

❓문자열로 변경하는 코드인데, 둘 중 어느 게 더 나은 건지 궁금합니다
- 둘 다 괜찮다고 생각하지만, 개인적으로 `String(Operator.allCases.map { $0.rawValue })` 부분을 더 선호합니다!

다른 질문과 관련된 부분은 코멘트로 남겨보았습니다!
확인 부탁드립니다!

2023-01-24 14:56 UTC, zdodev commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    var queue: Array<T>
해당 프로퍼티를 `private` 수준으로 구현하시는 부분이 고민이신 것 같습니다!
큐라는 자료구조를 사용하거나 테스트하기 위해서 `queue` 프로퍼티에 꼭 직접 접근해야 할까요?
큐가 제공하는 연산을 활용해보는 것은 어떨까요?

2023-01-24 14:56 UTC, zdodev commented on Calculator/Calculator/Model/ExpressionParser.swift
> +extension String {
해당 코드를 사용하기에 어떤 어려움이 있으셨는지 궁금합니다!

2023-01-24 14:56 UTC, zdodev commented on Calculator/QueueTests/QueueDoubleTypeTests.swift
> +    func test_dequeue가_제대로_되었는지_확인() {
메서드 내 `제대로` 라는 단어의 의미가 모호한 것 같습니다!
더 구체적인 이름으로 변경해볼 수 있을까요?

2023-01-26 08:06 UTC, llimental commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    var queue: Array<T>
queue 프로퍼티에 `private`를 적용하고, enqueue, dequeue를 활용한 유닛 테스트 진행해 보았습니다.

2023-01-26 08:08 UTC, ohdair commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    var queue: Array<T>
유닛 테스트의 함수명을 명확하게 변경하였습니다

2023-01-26 08:13 UTC, ohdair commented on Calculator/Calculator/Model/ExpressionParser.swift
> +extension String {
UML에서 제시된 split의 매개변수는 `Character`였으나 하고자 하는 동작은 Swift에서 제공되는 함수(`func components(separatedBy separator: [CharacterSet]) -> [String]`) 이기에 직접 만들기보다는 만들어진 걸 사용하였습니다

2023-01-27 10:06 UTC, zdodev approved these changes
안녕하세요. @llimental , @ohdair !

코멘트 확인하였습니다!
좋은 의견 달아주신 점이 좋았습니다!👍

Step 2 진행하시느라 고생하셨습니다!🎉

2023-01-27 10:06 UTC, zdodev commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    private var queue: Array<T>
`queue` 프로퍼티에 직접 접근하지 않는 방법을 생각해보셨네요!👍

2023-01-27 10:06 UTC, zdodev commented on Calculator/QueueTests/QueueDoubleTypeTests.swift
> +    func test_queue에_dequeue메서드로_요소가_제거되었는지_확인() {
보다 구체적이어서 좋습니다!👍

2023-01-27 10:07 UTC, merged