계산기 [STEP 2] D.O, Sunny
tasty-code/ios-calculator pull request #26
Opened 2023-01-25 07:50 UTC by SunnnySong

안녕하세요 콘(@protocorn93)😄  명절은 잘 보내셨나요? 저희는 오늘 명절 후 증후군에 걸린 것 같습니다,, 원래 Step2 PR을 저번주 금요일에 보내는 것이 목표였는데, 요구사항에 있는 UML을 보고 구조를 고민하고 설이 껴있어서 늦은 PR을 보내게 되었어요🥲
Step3에서는 요구사항을 더 완벽하게 구현할 수 있도록 노력하겠습니다!!!!!!!! 오늘도 행복한 하루 보내세요,콘😃

# 구현 사항

-   [x] UML을 기반으로 한 코드구현
    -   [ ] UML에 표기한 사항 모두 구현합니다
-   [x] 숫자와 연산자 입력에 큐 활용
    -   [x] 계산기가 입력받은 숫자와 연산자는 연산큐에 쌓입니다
    -   [ ] 0으로 나누기를 시도하는 경우 적절한 오류처리를 할 수 있도록 합니다

`0으로 나누기 시도시 오류처리` 사항은 STEP3 에서 함께 구현하고자 해요!🥲

`UML 표기한 사항 모두 구현` 중 CalculateItem protocol을 아직 적용하지 못했어요. 이 부분이 Step2 PR을 늦게 올리게 된 주범이에요.😡 저희가 UML을 보고 CalculateItem protocol을 사용해보려 했지만 아직 Protocol사용이 익숙하지 않아서 그런지 해당 프로토콜의 역할을 이해하기가 쉽지 않았어요. 그래서 일단 프로토콜을 제외하고 구현한 뒤 추후 CalculateItem protocol의 역할을 생각해보기로 했어요.

# 구현 세부사항 및 고민

### 1. count 함수 관련

Formula에서 실제 계산을 수행하는 result() 함수를 실행할 때, operands Queue에 저장되어있는 Node 갯수 만큼 dequeue를 실행해요. 때문에 CalculateItemQueue에 저장되어있는 Node의 갯수를 세는 count 함수를 LinkedList에 생성했어요.

이때 저희는 count()를 어떤 방식으로 구현하는 것이 제일 좋을지 고민에 빠졌어요.

**첫 번째 방식 >**
```swift
func count() -> Int { 
	guard var node = self.head else { 
		return 0 
	} 
	var count = 0 

	while node.next != nil { 
		count += 1 node = node.next! 
	} 
	return count 
}
```
첫 번째 방법은 node.next가 nil이 나오기 전까지 count를 올려 Node의 갯수를 계산하는 방법이에요.

**두 번째 방식 >**
```swift
final class LinkedList {
		// ...
    private var numberOfNodes: Int = 0
    
    func append(data: String) {
        if head == nil {
            head = ItemNode(data: data)
            tail = head
            
            numberOfNodes += 1
            return
        }
        // ...
        numberOfNodes += 1
    }
    
    func remove() -> String? {
        // ...
        numberOfNodes -= 1
        return result
    }
    
    func count() -> Int {
        return self.numberOfNodes
    }
}
```
numberOfNodes라는 변수를 만들고, Node를 append하고 remove할때 해당 변수를 +1, -1로 계산하는 방법이에요.

-   첫 번째 방식으로 count를 계산할 때 head부터 node.next가 nil이 될때까지 count를 올려야하기 때문에 O(n)의 시간복잡도를 갖는다 생각했어요.
-   두 번째 방법은 노드가 추가되고 삭제될 때, numberOfNodes의 변수 값이 바로 변경되므로 count 값을 가져올 때 O(1)의 시간이 걸려요.
-   각 함수별 ‘역할과 책임’을 생각했을 때, append()와 remove() 함수 안에 count기능을 넣는 것이 적절한지 고민이 되었어요. append() 함수에는 단순히 Node를 추가하는 함수만, remove()함수에는 단순히 Node를 제거하는 함수만 들어가야 하는걸까요?

### 2. split 구현 힘들었던 점

    💡 `“1+2+3”` 을 `[”1”, “+”, “2”, “+”, “3”]` 배열로 리턴하는 함수를 만들고자 하였고, 
    리턴값이 스트링배열인 함수를 구현하기 위해 split(separator: "+") 메서드를 사용하였어요.

**발생한 문제**
`[”1”, “+”, “2”, “+”, “3”]` 를 의도하였으나 `“+”` 를 기준으로 자르게 되어`["1", "2", "3"]` 가 리턴되었어요.
```swift
var userInput: String = "1+2+3" 
userInput.split(separator: "+") 
// ["1", "2", "3"]
```

**해결방법**
`replacingOccurrences` 를 사용해 `“+”` 에 공백을 넣어 `“ + “`로 만들어 주고, `“ “` 을 기준으로 `split` 하여 공백을 제거 및 분리하여 원하는 형태의 배열을 얻었어요.
```swift
var userInput: String = "1+2+3"

userInput.replacingOccurrences(of: "+", with: " + ") 
// "1 + 2 + 3"
userInput.replacingOccurrences(of: "+", with: " + ").split(separator: " ")
// ["1", "+", "2", "+", "3"]
```

**다시 발생한 문제**
원하는 리턴값을 얻었으나 `.split()` 으로 얻은 리턴값의 타입은 `Array<Substring>.Type` 으로, 최초에 원했던 `Araay<String>` 형태가 아니에요.

**해결방법**
`.split()` 대신 `.components()` 를 사용하여 리턴값으로 `Array<String>` 형태를 얻을 수 있었어요!
```swift
var userInput: String = "1+2+3"

userInput.replacingOccurrences(of: "+", with: " + ").components(separatedBy: " ")
// ["1", "+", "2", "+", "3"]
```

⚠️ 질문이 있어요..!

`“1+2”` → `[”1”, “+”, “2”]` 를 구현하기 위해 `“+”` 를 `“ + “`로 바꾸어서 (공백을 추가하여) `“ “`을 components 하는 방식으로 구현하였는데요!

만약 콘이라면 어떤 방식으로 구현하였을지 궁금해요! 🙋‍♂️
(더 좋은 방법이 있는지 궁금해서요🙏)

### 3. componentsByOperators

앞의 `String.split(with target: Character) → [String]` 을 이용하여 입력받은 값을 나누는 함수를 구현해 보았어요

-   입력값 : `"1+2*3-4”`
-   목표 : `[”1”, “+”, “2”, “*”, “3”, “-”, “4”]`

**발생한 문제**

-   예를 들어, `“+”` 를 사용하여 `split()` 하게 되면 리턴값이`[”1”, “+”, “2*3-4"]` , 즉 배열로 리턴이 되어요
-   다시 이 배열의 요소에 대하여 `“-”` 로 `split()` 하게 되면 `[["1"], ["+"], ["2*3", "-", "4"]]` 이 리턴되어요.

```swift
let input = "1+2*3-4"

let newInput = input.split(with: "+")
// ["1", "+", "2*3-4"]

let mapInput = newInput.map { $0.split(with: "-")}
// [["1"], ["+"], ["2*3", "-", "4"]]
```

**해결방법**

-   `map` 대신에 `flatMap` 을 사용해 보았어요.☺️
    -   `flatMap` : 2차원 배열을 1차원 배열로 리턴해준다
-   Operator 의 모든 case 에 대하여 split 할 수 있도록 `Operator.allCases.forEach`를 사용했어요.
```swift
static private func componentsByOperators(from input: String) -> [String] {
        var result: [String] = [input]
        
        Operator.allCases.forEach { operatorCase in
            result = result.flatMap {
                $0.split(with: operatorCase.rawValue)
            }
        }
        return result
    }

```

### 4. 폴더 분리
![image](https://user-images.githubusercontent.com/85678496/214507867-ec0ed907-7bfa-43e7-8d2f-90592c54edd4.png)

이번에 Step2를 진행하면서 파일들을 많이 생성했기 때문에 폴더로 정리할 필요성을 느꼈어요.

일단 폴더를 크게 Resources와 Sources로 나누어 보았어요.

❓ 혹시 콘이 생각하는 적절한 폴더 분리 방식은 무엇인가요?😁

2023-01-26 09:21 UTC, protocorn93 requested changes
두 분 모두 수고하셨어요! 스탭3애서 좀 더 상세하게 코멘트 남겨놓을게요. 이번 PR에선 코드 코멘트보단 바로 여기에 작성할게요! 

## 구현 세부사항 및 고민

> 1. count 함수 관련

일단 저는 count 함수가 필요해보이진 않아요. tail 프로퍼티가 있기 때문에 tail이 nil일 때가지 반복하면 되지 않을까 하는 생각이 드네요. `while let`을 활용해보면 좋을 것 같아요.

> 2. split 구현 힘들었던 점

이 역시 공백을 앞뒤로 넣는 방법보단 [`components(separatedBy:)`](https://developer.apple.com/documentation/foundation/nsstring/1410120-components) 메서드를 사용하면 쉽게 분리해낼 수 있을 것 같아요. `CharacterSet`을 활용해보시면 될 것 같아요. 

숫자만 추출한 배열, 연산자만 추출한 배열 두 개를 만들어낼 수 있고 각 배열을 mapping 해서 쉽게 Formula 객체를 만들 수 있지 않을까 싶어요! 그러면 `parse(from:)` 메서드 안에 인덱스로 연산자와 숫자를 구분하던 코드도 제거될 수 있을 것 같아요.

> 4. 폴더 분리

사실 폴더 정리는 정말 팀 바이 팀, 사람 바이 사람인 것 같아요. 물론 앱이 커질수록 이게 중요해지는데, 저도 여러분과 크게 다를 건 없어요! 도메인 단위로 디렉토리를 구성하고 그 안에서 다시 화면 단위로 구성하고 있어요. 여러 곳에서 사용하는 객체는 다시 해당 객체의 역할별로 디렉토리 구조를 가져가곤 해요. `UseCases`, `Repositoires` 등등

2023-01-26 09:21 UTC, protocorn93 commented on Calculator/Calculator/Sources/Model/ExpresstionParser.swift
> +    func parse(from input: String) -> Formula {
1. `ExpressionParser`를 열거형으로 구현하신건 UML을 따르신걸까요?
2. `parse(from:)` 메서드를 호출하려면 `ExpressionParser` 인스턴스가 필요해보이는데, static으로 정의되어야 하지 않을까요?

2023-01-26 09:21 UTC, protocorn93 commented on Calculator/Calculator/Sources/Model/ExpresstionParser.swift
> +enum ExpresstionParser {
ExpressionParser 아닐까요?!

2023-01-26 09:21 UTC, protocorn93 commented on Calculator/Calculator/Sources/Model/LinkedList.swift
> +    func append(data: String) {
타입을 다시 명시적으로 지정한 이유가 궁금해요.

2023-01-26 09:21 UTC, protocorn93 commented on Calculator/Calculator/Sources/Model/Formula.swift
> +        return middleResult
`while let` 문을 활용하면 좀 더 간결하게 코드 수정이 가능할 것 같아요!

2023-01-27 02:23 UTC, doshkor commented on Calculator/Calculator/Sources/Model/LinkedList.swift
> +    func append(data: String) {
기존 방식은 노드속성인 Value 구조체에 연산자와 피연산자를 담아 하나의 큐를 사용하였으나, 바뀐 방식은 연산자큐와 피연산자큐를 분리하여 생성하였어요!

2023-01-27 02:27 UTC, doshkor commented on Calculator/Calculator/Sources/Model/ExpresstionParser.swift
> +enum ExpresstionParser {
오타를 수정하고 push 하였으나...  test 브랜치에 push 하였더라구요..

브랜치 확인의 중요성을 깨닫게 되었어요 🥲

2023-01-27 02:30 UTC, doshkor commented on Calculator/Calculator/Sources/Model/ExpresstionParser.swift
> +    func parse(from input: String) -> Formula {
1. 네. 요구사항이였어요..!

2. `parse(from:)` 및 `componentsByOperators(from: )` 모두 `static` 으로 구현하였으나.. 
     test 브랜치에 push 한 것을 확인하였습니다 🥲
     다음 PR 때는 다시 한번 확인하고 보내는 습관을 가져야 할 것 같아요!

2023-01-27 12:59 UTC, SunnnySong commented on Calculator/Calculator/Sources/Model/Formula.swift
> +        return middleResult
while let 문을 생각해보지 못했어요! while let문을 활용하여 수정했습니다. 감사합니다😁

2024-06-17 08:21 UTC, closed without merging