계산기 [Step 2] iyeah, Jenna
tasty-code/ios-calculator pull request #27
Opened 2023-01-25 08:10 UTC by ueunli

Jake 안녕하세요! @jryoun1
행복한 연휴 보내셨나요 😇 늦었지만 새해 복 많이 받으시고 건강한 한 해 보내시길 바라요 ✨
STEP 2는 정해진 UML대로 코드를 구현해야 했는데
UML 해석에도 꽤 오랜 시간이 걸렸고, 구현은 했지만 사용하지 못한 부분도 있어요..!
아래에서 더 자세하게 설명드리도록 하고 이번 스텝도 리뷰 잘 부탁드려요 감사합니다 🐣

　
# 👾 구현한 사항
- UML에 따른 타입별 구현사항

    | 타입 | 이름 | 요약 |
    | ---:|:--- |:--- |
    | protocol | CalculateItem | 빈 프로토콜 |
    | extension | Double+ | CalculateItem 채택 |
    | extension | String+ | split(with:) 메서드 — 사용하지 않음 |
    | enum | CalculatorError | 0으로 나눌 경우의 에러 |
    | enum | Operator | CalculateItem 채택 |
    | enum | ExpressionParser | 완성된 계산식(문자열)에서 연산자·피연산자를 추출하여 Formula형태로 반환하는 타입메서드 |
    | struct | TemporaryInput | C/E로 제거 가능한 직전입력값을 정제 및 저장 |
    | struct | CalculatorItemQueue | 정제된 직전입력값을 순서대로 넣고 빼는 큐 - CalculateItem를 채택한 타입만 제네릭요소로 받음 |
    | struct | Formula | 연산자, 피연산자를 별개의 큐에 저장 및  최종 계산 |
- Unit Test
파일별로 테스트를 진행하였어요!
![](https://i.imgur.com/pXXfg8j.png)

　
　
# 👾 고민했던 사항
## 1. Formula
> **`reduce`함수**
```
(1...operators.count()).reduce(...) {...}
```

`operands`큐, `operators`큐 둘 중 하나에 `.reduce(_:_:)`를 쓸까 고민했지만, 
그러면 그 큐는 실질적으로 dequeue가 아니라 forEach스럽게 각 요소를 순회하게 되어요...
자료구조를 공부해서 적용하는 첫 프로젝트인 만큼 둘 모두 Queue로서의 정체성을 최대한 활용해보고 싶었기에 아래와 같이 작성했는데, 
- 다소 무의미한 임의의 콜렉션(범위연산자: `1...operators.count()`)에 `.reduce(_:_:)`를 적용
- `.reduce(_:_:)` 내부에서 
`operands.dequeue()`와 `operators.dequeue()`를 각각 실행

Queue스러움을 살리려다가 reduce가 부적절하게 구현된 것은 아닌지(사용하지 않을 값들에 적용해서) 의문이 들었어요..!
좋은 대안이나 알아두면 좋을 부분이 있다면 조언 부탁드려요🥲

　
## 2. CalculatorItemQueue
> 시간복잡도 개선을 위한 `reversedItems` 생성
* dequeue를 위한 Array의 removeFirst()는 시간복잡도 O(n)이에요.
* Array의 reversed()는 시간복잡도 O(1)로, 
이것을 이용하여 dequeue를 할 때 배열을 뒤집어서 removeLast()로 시간복잡도를 낮추기 위해 고려하였어요.
* 뒤집어서 dequeue하기 위해 `reversedItems`라는 계산속성을 따로 만들었어요.
`items`를 자동으로 뒤집어서 가져오거나 세팅해줘요.
* step1에서 공부했던 더블스택의 아이디어를 일부 가져왔어요.
(dequeue시에만 쓰이므로 전부를 차용하지는 않았어요) 

　
## 3. TemporaryInput
> 지난 스텝에서 고민했던 '임시로 담아두는 배열'을 구조체로 따로 구현했어요
> 이유와 해당 기능은 아래와 같아요
* 연산자나 부호변경이 피연산자 입력 중간중간에 추가되는 경우에 대비하여
   * 부호변경이 언제 눌리든 Bool타입으로 부호가 토글돼요
   * 피연산자가 비어있을 때 연산자가 추가로 입력되면 연산자가 교체돼요
   * 피연산자가 비어있지 않을 때 연산자가 입력되면 (VC에서) 지금까지 입력된 `연산자+부호+피연산자`를 조합하여 (`CalculatorItemQueue`에) 내보내요
* `CE`를 입력받았을 때 직전입력값만 삭제하기 용이하도록
   * (VC에서) 이 구조체 인스턴스를 초기화하기만 하면 되도록 따로 만들었어요

　
## 4. ExpressionParser
> String extension 미사용

* UML에 맞춰 구현해야 했기에 String extension으로 `split(with:)`를 구현했지만 사용하지 않았어요
*  위는 매개변수가 CharacterSet이나 [Character]가 아니라 Character, 
즉 외부에서 +", "−", "÷", "×"에 대해 4번씩 호출해줘야 하는 메서드 같았어요 
(오래 고민해 봤지만 다른 해석을 찾지 못했어요..🥲)
*  그보다는 아래와 같이 components로 4가지 문자에 대해 한번에 분리해주는 편이 가독성/효율성 면에서 유리해 보였어요
```
input.components(separatedBy: ["+", "−", "÷", "×"])
```

　
## 5. Operator
Character원시값들 중, `뺄셈 기호`가 `음수를 뜻하는 부호`와 같아서 이 둘을 어떻게 구분해줘야 할까 고민하다가 
스토리보드에 기 구현된 버튼이름에서 아이디어를 얻어 일반 부호(흔한 하이픈: `-`)와 연산자 부호(특수문자: `−`)를 구분해서 사용하기로 했어요

　
## 6. 유닛 테스트
저번 pr에서도 말씀드렸던 것처럼 테스트를 진행하려면 본래 소스코드를 일부 수정(접근제어 등..)해야 될 경우 어떻게 하면 좋을지 고민이 많았어요.
특히 `ExpressionParserTests`에서는 XCTAssertEqual을 쓰기 위해 대상이 되는 타입들에 `Equatable`프로토콜을 적용해야만 했는데, 의논 끝에 해당 파일 상단에 간단한 확장을 추가했어요. 
이렇게 해도 되는 건지, 이럴 때 현업에서는 보통 어떻게 하는지 조언 부탁드려요!!

　
　

2023-01-26 05:29 UTC, corykim0829 requested changes
제가 실수로 여기에 리뷰했네요 죄송합니다!

2023-01-26 05:29 UTC, corykim0829 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +extension Formula: Equatable {
Formula가 Equatable을 채택할 필요는 없어보여요!
Formula의 내부 프로퍼티들이 모두 접근 가능하기 때문에 직접 비교하는게 좋을 것 같습니다!

2023-01-26 05:29 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        try (1...operators.count()).reduce(0.0) { initialResult, _  in
0으로 시작하게 되면 덧셈이 아닌 연산자들은 모두 결과가 다르게 나오네요! 수정이 필요해보입니다!

2023-01-26 05:29 UTC, corykim0829 commented on Calculator/Calculator/Model/ExperssionParser.swift
> +        input.components(separatedBy: ["+", "−", "÷", "×"])
components 메소드도 내부에서는 split을 여러번 돌리는 것이기 때문에 여유가 있다면 split 메소드를 이용해서 구현해보는 것도 좋을 것 같네요 :)

2023-01-26 05:29 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        try (1...operators.count()).reduce(0.0) { initialResult, _  in
Range 선언 부분에서는 `0..<operators.count()`가 조금 더 일반적인 방법이라 추천드립니다!

2023-01-26 13:50 UTC, jryoun1 requested changes
iyeah, Jenna 설연휴는 잘 보내셨나요? 맛있는 건 많이 드시고 오셨겠죠? ㅎㅎ
계산기 프로젝트는 이번 주가 마지막이지만, 설연휴 충전하신 뒤에 앞으로의 프로젝트도 화이팅하시길 바랄게요 🙏🏻
step2 고생하셨습니다!

pr에 고민하신 부분들과 코드를 작성하신 이유들을 잘 작성해주셔서 리뷰를 잘 드릴 수 있었던 것 같네요 👏
고민하신 부분들에 대해서는 코드부분에서 코멘트를 달아두었습니다!
확인부탁드려요~

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				3B67C40E297A329000ABCD97 /* Formula.swift */,
폴더 그룹핑을 조금 더 세분하게 하면 좋을 것 같아요 🙏🏻
예를 들어서 extension은 extension끼리, model은 model끼리 이렇게 그룹핑하면 찾기 쉬울 것 같습니다.

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case cannotDivideByZero
0으로 나눴을 때의 에러를 추가해주셨군요 👏

`0으로 나누면 안된다` 라는 에러 네이밍도 좋지만, 아래와 같은 네이밍은 어떨까요? 
```swift
case divideByZero 
```

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
시간복잡도 개선을 위해 적용하신 부분이군요 👏💯
O(n)도 큰 시간 복잡도는 아니지만, 이를 개선해서 상수의 시간복잡도를 가지게 하기 위해서 고민하신 부분이 좋은것 같습니다.

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Item: CalculateItem> {
제네릭을 사용하셨네요 👍🏻

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: Character, CaseIterable, CalculateItem {
가독성 있게 Operator 타입을 구현해주셨군요 👍🏻💯
calculate 함수도 switch - self를 사용해서 잘 구현해주셨네요 👏

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/TemporaryInput.swift
> +    }
연산 프로퍼티로도 구현이 가능할 것 같은데 함수로 구현해주신 이유가 궁금합니다 🙋‍♂️
함수와 연산 프로퍼티를 사용하는 기준이 따로 있으신가요?

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +final class CalculatorItemQueueTests: XCTestCase {
파일이름과 클래스 명도 같이 수정해주셨군요! 디테일을 챙겨주시는 것 좋네요 👏

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +}
고민하신 부분처럼 이 테스트에서 필요하다면 상단에 extension을 통해서 구현할 수도 있을 것 같고, 
해당 테스트에서 테스트하고 싶은 내용은 올바르게 분리되는지인 것 같습니다.

따라서 메서드를 2개로 나눠서 연산자가 제대로 분리되고 값이 같은지 확인하고, 피연산자가 제대로 분리되어서 값이 같은지 확인하는 방법도 있을 것 같긴하네요.

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/ExperssionParser.swift
> +            .forEach { operands.enqueue(item: Double($0) ?? 0) }
실제로 0을 입력한 경우와 Double로 변환하지 못해서 default로 0인 것이 있을 것 같은데 두 개는 따로 구분할 필요가 없을까요?

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/ExperssionParser.swift
> +    }
componentsByOperators를 잘 구현해주셨네요. 
만약 split을 사용하지 않고, split 메서드가 불필요하다면 지워도 되지 않을까요?

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/Calculator/Model/Formula.swift
> +            return anOperator.calculate(lhs: initialResult, rhs: anOperand)
여기가 고민하신 formula 부분이군요.
말씀주셨던 것 처럼 두 분이 큐를 queue답게 사용하고 싶으셔서 위와 같이 구현을 하신 것 같고, 그러한 이유라면 괜찮아보이긴합니다. 

다만 지금 1부터 operators.count까지 인데, 사용자가 계산기에 입력을 `1 + 2 - 4 + =` 이런식으로 했다면 지금으로서는 문제가 발생할 것 같긴하네요. 이 부분은 추후에 개선이 필요해보이긴합니다. 
물론 해당 케이스는 예외 케이스이고 그러한 부분을 처리해주는 부분은 ExpressionParser쪽에 operand, operator의 짝이 맞는지 확인하는 부분이 있어야할 것 같아보입니다.

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/CalculatorTests/FormulaTests.swift
> +        let expectation = 0.0 + 1.0 + 2.0
1 + 2를 입력했을 것이라고 기대되지만, 실제 expectation은 0 + 1 + 2 인 것은 기대와는 다른 것 같습니다. 물론 결과는 같지만, `+` 연산자가 두 번 enqueue해주는 것이 이상한 것 같습니다.

2023-01-26 13:50 UTC, jryoun1 commented on Calculator/CalculatorTests/FormulaTests.swift
> +    }
에러가 발생하는 케이스까지 테스트 좋네요 ㅎㅎ 💯

2023-01-27 01:18 UTC, ueunli commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +}
생각도 못한 방법인데 조언 주셔서 감사해요 !!
말씀해주신 대로 Formula 자체가 아니라 그 안의 큐가 가지고 있는 (이미 Equatable을 준수하는 요소들의) 배열끼리 비교함으로써 확장 없이 문제를 해결할 수 있었어요🙆‍♀️

2023-01-27 01:18 UTC, iyeahh commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				3B67C40E297A329000ABCD97 /* Formula.swift */,
extension끼리 그룹핑하여 폴더를 만들었는데, 혹시 protocol도 갯수가 많아지면 따로 그룹핑을 하는지 궁금합니다 🤔

2023-01-27 01:18 UTC, iyeahh commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case cannotDivideByZero
네이밍 추천 감사합니다! 수정하였어요 🙂

2023-01-27 01:53 UTC, ueunli commented on Calculator/Calculator/Model/TemporaryInput.swift
> +    }
당시에 연산 프로퍼티로 구현하면 partialOperands가 변경되면 자동으로 같이 연산이 돌아간다는 점에서(lazy도 쓸 수 없으니) 비효율적이지 않을까 생각했던 것 같아요..!
사실 기준이 따로 있지는 않았어요🥲 확실히 더 생각해봐야 할 부분인 것 같아요 물어봐주셔서 감사합니다😄
makePair()도 같은 이유로 메서드로 구현했었는데, 스텝 진행하면서 같이 고민해볼게요!

2023-01-27 02:00 UTC, iyeahh commented on Calculator/Calculator/Model/ExperssionParser.swift
> +            .forEach { operands.enqueue(item: Double($0) ?? 0) }
구분할 필요가 있다는 것은 분명히 인지하고 있으나, 구분 기준을 정의하려면 로직 예외처리를 먼저 고민해봐야 할 것 같았어요..!
그래서 Double의 형식이나 입력 예외에 관해서 오래 얘기를 해봤는데 ViewController의 로직까지 생각해봐야 명확해질 부분인 것 같아서 잠시 보류해두었습니다 😇
말씀해주신 부분 꼭 기억해두었다가 결론이 나면 해당 부분에 옵셔널 바인딩 혹은 에러처리 적용하도록 하겠습니다!

2023-01-27 02:22 UTC, iyeahh commented on Calculator/Calculator/Model/ExperssionParser.swift
> +    }
UML대로 구현하는 것이 필수 조건이어서 일단 작성해둔 부분이었어요!
지워도 된다면 지우는 것도 전혀 상관없습니다..!

2023-01-27 02:41 UTC, ueunli commented on Calculator/Calculator/Model/Formula.swift
> +            return anOperator.calculate(lhs: initialResult, rhs: anOperand)
pr에 빠뜨린 내용이 있어요..! 
저희가 가장 고민했던 사항 중 하나가 연산자들-피연산자들의 쌍을 균등하게 맞추는 거였는데, 
이를 위해 총 계산식의 앞에 `0+`를 디폴트로 넣어주기로 했어요. 방법은 아래와 같아요 ㄱ

- `1`. '연산자-피연산자' 쌍 조합을 맞추기 위해 첫 피연산자의 앞에 `+`를, 
- `2`. 온전한(계산 가능한) 계산식을 완성하기 위해 그 앞에 또 `0`을, 

`1번`은 TemporaryInput의 `partialOperator`의 기본값을 `+`로 줌으로써, 
`2번`은 Formula의 result()에서 `initialResult`를 `0.0`으로 줌으로써 해결했어요

1번구현, 그리고 위에서 언급하신 대로 Double? 변환실패 시 특별한 로직 없이 기본값만 0.0으로 주었으므로
현재로서는 Formula의 result() 내부에서 연산자큐, 피연산자큐의 요소 개수가 달라질 일은 없을 것 같아 짝 개수는 검증하지 않았어요

그렇더라도 발생 가능한 모든 케이스는 검증 및 처리해주는 편이 안전하기에 말씀하신 부분이 맞는 것 같아요.
다음 스텝 도전하면서 Double? 변환실패 시 예외처리를 정의하게 되면 이 부분 함께 고려하여 수정하겠습니당 🫠

2023-01-27 02:42 UTC, ueunli commented on Calculator/CalculatorTests/FormulaTests.swift
> +        let expectation = 0.0 + 1.0 + 2.0
위 답변과 같습니다🙋🏻‍♀️

2023-01-27 09:29 UTC, jryoun1 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				3B67C40E297A329000ABCD97 /* Formula.swift */,
그룹핑을 하는게 결국 프로젝트에서 폴더명을 보고 어디에 뭐가 있겠구나를 빠르게 찾아가기 위한 것이라서, 목적에 맞는 것들끼리 같이 그룹핑하면 될 것 같아요. 

그게 어떤 한 도메인(e.g. 검색, 메인, 결제 등등)의 protocol들이 될 수도 있고, view, viewModel들이 될수도 있겠네요!

2023-01-27 09:31 UTC, jryoun1 commented on Calculator/Calculator/Model/ExperssionParser.swift
> +    }
요구사항에 있긴하지만, 만약 불필요한것 같다면 그 이유와 함께 이야기 하고 그것이 납득된다면 충분히 지워줄 수 있을 것 같아요.
사용하지 않는 코드를 굳이 남겨둘 필요는 없으니까요 🙂

2023-01-27 09:34 UTC, jryoun1 commented
잘 수정해주셨고, 충분한 이유들을 설명해주셨네요 👏👍🏻 
step2 고생하셨습니다 ㅎㅎ merge 하겠습니다!

2023-01-27 09:34 UTC, merged

2023-01-27 09:35 UTC, jryoun1 commented on Calculator/Calculator/Model/Formula.swift
> +            return anOperator.calculate(lhs: initialResult, rhs: anOperand)
이미 알고 계셨다면 다행입니다 ㅎㅎ 👍🏻💯
추후에 반영해서 진행해주시면 될 것 같습니다!!