[STEP 1] Rookie, Ireu
tasty-code/ios-calculator pull request #4
Opened 2022-09-07 01:21 UTC by chaeyoon1101

@jaemuYeo 리뷰 잘 부탁드립니다

# STEP 1 수행한 것
- UML 작성
- `CalculatorItemQueue` 생성
- `Queue` 생성
-  `CalculatorItem` 프로토콜 생성

# UML
![image](https://user-images.githubusercontent.com/84975077/188596766-12cd660d-52fd-4bbc-9549-bf6e24a7a17b.png)

2022-09-07 01:39 UTC, jaemuYeo requested changes
루키 이르 스텝1 고생많았습니다 👍
코드에 개별적인 코멘트 남겨놓았습니다!

## 추가적인 전달내용
쥬스메이커처럼 계산기프로젝트도 MVC에 맞는 그룹별 파일분리를 해보면 어떨까요??

## TDD
테스트케이스를 작성할때
`given when then 패턴`에 대해 조사해보고 적용시켜보세요💪

## Queue타입
여러 자료구조들은 `시간복잡도`의 개념이 조금은 필요하답니다!
필요하다면 같이 조사해보는 시간을 가지면 좋을거같아요 ㅎㅎ
List를 활용한 Queue타입과 지금처럼 일반적인 Queue타입 구현은 
어떤 차이가 있고 List를 활용하였을때 어떤 이점들이 있을까요??

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/AppTests/AppTests.swift
> +class AppTests: XCTestCase {
테스트 파일을 만들때는 테스트하려는 `객체의 이름 + Tests`으로 테스트 객체네이밍과 파일명을 지정해주면 좋습니다 😀
그룹은 현재 앱의 네임을 써서 `CalculatorTests`로 해주세요~

‼️ 내가 만든 큐가 정상적으로 작동하는지 테스트도 진행해보세요 ㅎㅎ

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/Calculator/AppDelegate.swift
> +//  Created by yagom.
이런 부분도 여러분들이 생성한 파일과 다른 부분이 있네요!
소소한 부분이지만 수정해주면 좋습니다 😀

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/Calculator/CalculatorItemQueue.swift
> +class CalculatorItemQueue: CalculatorItem {
이름 그대로 CalculatorItem`Queue`인데 Queue타입을 따로 설계한 이유가 있나요?

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +class Queue<T> {
이 타입은 왜 class로 선언되었나요?
제네릭을 활용하였군요 👍 일반적으로 T를 사용해도되지만
Element나 다른 것들을 통해 조금 명확하게 해주는 것도 좋은 방법이랍니다 🤗
ex) `Queue<Element>`

이 타입에는 네가지 기능들만 있으면 될까요?
요소에 값이 있는지 없는지에 대한 것과
요소의 개수를 알 수있는 기능도 가지고 있으면 좋을 것같아요!

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +    public var list: [T] = []
아래를 포함해 왜 접근제어를 public으로 하였나요??

2022-09-07 01:39 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +        list = []
removeAll이라는 메서드를 활용해보세요~
list.removeAll()

2022-09-07 01:58 UTC, Y00ujin commented on Calculator/Calculator/AppDelegate.swift
> +//  Created by yagom.
네! 수정했습니다!

2022-09-07 01:58 UTC, Y00ujin commented on Calculator/AppTests/AppTests.swift
> +class AppTests: XCTestCase {
네! 네이밍 변경하였습니다!

2022-09-07 02:05 UTC, Y00ujin commented on Calculator/Calculator/CalculatorItemQueue.swift
> +class CalculatorItemQueue: CalculatorItem {
CalculatorItemQueue에서 numbers와 operators에 enqueue, dequeue하는 것보단 Queue라는 타입을 하나 만드는 게 좀 더 깔끔할 거 같아서 Queue 타입을 설계했습니다..!

2022-09-07 02:07 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +class Queue<T> {
Element로 변경하였습니다! isEmpty와 getListCount 함수 추가하였습니다!

2022-09-07 02:11 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +    public var list: [T] = []
접근제어에 대해 잘못 이해하고 있었던 것 같습니다 😂

함수는 모두 기본 접근 제어로 수정하였고, list는 Private으로 선언한 후 함수를 통해 접근하는 방식으로 수정하였습니다!

2022-09-07 02:11 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +        list = []
네! 수정하였습니다!

2022-09-07 05:47 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +class Queue<T> {
getListCount는 간단히 count라는 연산프로퍼티로 표현할 수 있습니다!

2022-09-07 05:48 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +    public var list: [T] = []
좋아요 👍

2022-09-07 06:41 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +class Queue<T> {
수정하였습니다!

2022-09-07 08:03 UTC, jaemuYeo requested changes
루키 이르 코멘트 반영하느라 고생했습니다!
다만 아쉬운 부분이 남아 한 번 더 고민해보면 좋을 거같아 다시 요청해요~
1. MVC패턴에 맞는 그룹(파일) 분리
2. Unit Test
- given when then 패턴 중 when이 빠짐
- 테스트 케이스들에 대한 네이밍 고민(given when then의 흐름대로 네이밍하기)
- 네이밍 한글 가능 (띄어쓰기 또는 구분점은 언더바로 표시)

2022-09-07 08:03 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +class Queue<Element> {
이 타입은 구조체로 선언되어도 될 것같아요!
그 이유에 대해 설명해주실 수 있나요?

2022-09-07 08:03 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +        return list
반환타입이 있더라도 이러한 단행 함수는 return 키워드를 생략할 수 있습니다!
적어도 같은 파일 내에서는 그 컨벤션을 맞춰주세요~
간단한 요소를 반환하는 행위는 연산프로퍼티로도 구현할 수 있을 것같아요!

2022-09-07 08:03 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +    func dequeue() {
Queue자료구조의 특징은 선입선출 입니다 (FIFO)
근데 값을 빼낼때 마지막 요소를 반환하군요! 스택에 더 가까운 것 같아요
그리고 만약 배열에 값이 없다면 어떻게 될까요?

2022-09-07 08:03 UTC, jaemuYeo commented on Calculator/Calculator/Queue.swift
> +    func isEmpty() -> Bool {
이 친구도 연산프로퍼티로 구현해도 될 것같습니다!

2022-09-08 01:13 UTC, chaeyoon1101 commented on Calculator/Calculator/Queue.swift
> +class Queue<Element> {
class에서 struct로 변경했습니다

2022-09-08 01:13 UTC, chaeyoon1101 commented on Calculator/Calculator/Queue.swift
> +        return list
연산프로퍼티로 다시 구현했습니다

2022-09-08 02:03 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +    func dequeue() {
list에 값이 있을 때 list의 첫 값을 제거하는 방식으로 변경하였습니다!

2022-09-08 02:04 UTC, Y00ujin commented on Calculator/Calculator/Queue.swift
> +    func isEmpty() -> Bool {
변경했습니다!

2022-09-08 05:07 UTC, jaemuYeo reviewed
이르 루키 스텝1 고생많았습니다!!
머지진행할게요 👍
몇 가지 내용만 코멘트 남겨놓았으니 확인해주세요!!
다음 스텝으로 넘어가기전 
[참고자료](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift/v3.0/chapters/8-queues)를 보며 두분이 구현한 큐와 비슷한 형태를 가졌는지
 한번 되돌아보는 시간을 가져도 좋을 거같아요 😀

2022-09-08 05:07 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_Queue의_Dequeue가_작동하는지() {
테스트 네이밍은 과정을 전부 적어주면 좋아요! 길어져도 좋습니다
test_빈큐에_3을인큐하고_디큐했을때_리스트는비어있다
equal메서드의 매개변수에 값들은 상수에 저장해서 넣어주면 좋아요!
그것이 when과 then의 조합이면 더 좋구요!

2022-09-08 05:07 UTC, jaemuYeo commented on Calculator/Calculator/Model/Queue.swift
> +    mutating func dequeue() {
dequeue한 값은 빼는 순간 그냥 사라지는 건가요?
아니면 반환되서 어딘가에 저장되어야 할까요?

2022-09-08 05:07 UTC, jaemuYeo commented on Calculator/Calculator/Model/Queue.swift
> +    mutating func removeAll() {
clear라는 네이밍도 깔끔할 거같아요!
꼭 수정하지 않아도 좋아요~

2022-09-08 05:07 UTC, merged

2022-09-13 03:17 UTC, Y00ujin commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_Queue의_Dequeue가_작동하는지() {
수정하겠습니다!

2022-09-13 03:18 UTC, Y00ujin commented on Calculator/Calculator/Model/Queue.swift
> +    mutating func removeAll() {
변경했습니다!