[STEP 1] 씨유, 송만이
tasty-code/ios-calculator pull request #6
Opened 2022-09-07 05:14 UTC by Schro2109

@jaemuYeo 
# 작업 내용
1. CalculateItem 프로토콜 생성
2. CalculatorItemQueue 구현
3. CalculatorItemQueue를 대상으로 한 Unit Test 생성
# UML

2022-09-07 06:21 UTC, jaemuYeo requested changes
씨유 송만이 스텝1 고생많았습니다! 👍
현재 Queue타입을 기본적으로 구현해주었는데
자료구조 List를 활용한 Queue타입과 현재 구현한 것은 어떤 차이점이 있을까요?
그리고 List를 통해 구현했을 때의 이점은 어떤게 있을까요?
시간 복잡도에 대해 조사해보았으면 좋겠어요~

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/Calculator.swift
> +protocol CalculateItem {
이 프로토콜토 따로 파일분리하면 좋을 것같아요 😀
그리고 파일네임과 타입 네임을 맞춰주세요!

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/Calculator.swift
> +struct CalculatorItemQueue: CalculateItem {
queue타입을 구조체로 선언한 이유가 궁금하군요!

마지막 요소를 제거하거나 배열의 카운트를 알려주는 것도 있으면 좋을 것 같아요 🤔

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/Calculator.swift
> +    private var itemStorage: [String] = []
이 queue타입을 활용해 String이 아닌 다른 타입도 활용하려면 어떻게 할 수 있을까요?
네이밍 너무 좋아요 💯

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/Calculator.swift
> +        return itemStorage.removeFirst()
이렇게 바로 Return하는 경우 return 키워드를 생략해도 된답니다 😀

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/Calculator/Model/Calculator.swift
> +        if itemStorage.isEmpty {
꼭 이런 조건이 없더라도 배열의 값에따라 알아서 반환해주지 않을까요?

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    override func setUpWithError() throws {
여기서 표현한 두 오버라이딩 메서드의 역할에 대해 알려줄 수 있나요?

2022-09-07 06:21 UTC, jaemuYeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test() {
여러 테스트케이스를 작성하신 것에 박수를 드립니다 !! 👏
다만 `given when then패턴`을 조사해보고 적용해서 다시 한번 작성해보면 좋을 것같아요!

2022-09-08 02:27 UTC, seunghui5247 commented on Calculator/Calculator/Model/Calculator.swift
> +struct CalculatorItemQueue: CalculateItem {
마지막 요소 제거와 배열의 카운트를 알려주는 메서드를 추가했습니다.

2022-09-08 02:27 UTC, seunghui5247 commented on Calculator/Calculator/Model/Calculator.swift
> +        return itemStorage.removeFirst()
네 수정하겠습니다.

2022-09-08 02:28 UTC, seunghui5247 commented on Calculator/Calculator/Model/Calculator.swift
> +protocol CalculateItem {
네 알겠습니다

2022-09-08 02:29 UTC, Schro2109 commented on Calculator/Calculator/Model/Calculator.swift
> +struct CalculatorItemQueue: CalculateItem {
CalculatorItemQueue는 상속할 일이 없고 가이드라인에서 기본적으로 struct를 사용하라는 것이 있어 구조체로 선언해봤습니다.
그리고 마지막 요소를 제거하는 removeLast 함수와 카운트를 알려주는 count 함수 추가했습니다!

2022-09-08 02:31 UTC, seunghui5247 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    override func setUpWithError() throws {
setUpWithError 메서드는 각각의 test case가 실행되기 전마다 호출되어 각 테스트가 모두 같은 상태와 조건에서 실행될 수 있도록 해주는 메서드이고, tearDownWithError 메서드는 setUpWithError 메서드에서 설정한 값들을 해제해주는 메서드입니다

2022-09-08 02:36 UTC, Schro2109 commented on Calculator/Calculator/Model/Calculator.swift
> +        return itemStorage.removeFirst()
오 처음 안 사실이네요
코드에 반영해봤습니다!

2022-09-08 02:37 UTC, Schro2109 commented on Calculator/Calculator/Model/Calculator.swift
> +    private var itemStorage: [String] = []
[Any] 타입으로 변경해 다른 타입도 들어갈 수 있도록 변경했습니다!

2022-09-08 02:37 UTC, Schro2109 commented on Calculator/Calculator/Model/Calculator.swift
> +        if itemStorage.isEmpty {
확실히 조건문은 필요가 없던 부분이였네요
itemStorage.isEmpty를 바로 반환하는 형식으로 바꿨습니다!

2022-09-08 02:38 UTC, Schro2109 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test() {
패턴에 맞춰 다시 작성했습니다!

2022-09-08 02:59 UTC, jaemuYeo requested changes
씨유 송만이 너무 잘 해주었어요!!
다만 큐타입에 제네릭을 활용해보면 좀더 다양한 타입에 대응할 수 있을 것같아요!
[참고자료](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift/v3.0/chapters/8-queues)를 보고 학습후에 한 번 더 수정해보면 좋을 것같아요 😀

2022-09-08 02:59 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> Any {
배열에 값이 있을수도 있고 없을 수도있는데 없는경우 dequeue를 하면 어떤 일이 발생할까요?
removeLast도 마찬가지 입니다!

2022-09-08 08:22 UTC, Schro2109 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> Any {
타입을 제네릭으로 변경하고
값이 없는 경우 nil을 반환하고 값이 있는 경우 removeFIrst()를 실행한 결과를 반환하도록 수정했습니다!

2022-09-08 08:44 UTC, jaemuYeo reviewed
씨유 송만이 스텝1 고생많았습니다!!
다음 스텝을 진행하며 Queue타입이 조금은 변경될수있지만
현재는 Queue타입의 기능을 충실히 해주고있기때문에 머지진행할게요!

2022-09-08 08:44 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
간단히 요소를 확인하는 count나 isEmpty는 연산프로퍼티로 구현해도 될것같아요 😀
다음 스텝에서 현재구현한 것들을 사용해보면서 필요에따라 반영해보세요!

2022-09-08 08:45 UTC, merged

2022-09-08 08:50 UTC, Schro2109 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
넵 알겠습니다!