[STEP1] 우노,또바기
tasty-code/ios-calculator pull request #9
Opened 2022-09-08 03:00 UTC by eunho8713

@jaemuYeo 리뷰 부탁드립니다!

# STEP1 수행 내용

- Queue타입 구현을 위한 UML작성
- CalculatorItemQueue타입 구현
- CalculateItem Protocol생성
- Unit Test 추가 및 사용

## 고민되었던 내용
- Queue를 처음으로 접한 것이라 아직 어떨때 사용하는지, List와 비교하였을때 왜 이번프로젝트에서 Queue를 사용해야하는지가 의문점으로 남아있습니다.

# UML
<img src="https://cdn.discordapp.com/attachments/793123892888600616/1017240268451356742/2022-09-08_10.04.14.png">

2022-09-08 03:33 UTC, jaemuYeo requested changes
또바기 우노 고생했어요! 
고민했던 부분중 List와 Queue타입의 사용에 대한 의문점이 있었는데
둘중 하나를 선택하는 것이 아닌 Queue타입을 위한 List 타입 
즉, List를 활용한 Queue타입을 만들어보라는 제시였습니다!
List를 활용해서 Queue를 만들었을때의 이점이 어떤것이 있을까요??

UML에서 화살표의 방향도 한번 고민해보면 좋을거같아요!

2022-09-08 03:33 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
큐타입은 왜 클래스로 선언하였나요?

제네릭의 활용 좋아요! 제네릭을 사용한 이유가 있나요?

2022-09-08 03:33 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var data: [T?] = []
배열 타입이 왜 옵셔널인가요?

2022-09-08 03:33 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
여기 아래는 전부 접근제어가 public이군요!
public인 이유를 알려줄수있나요?🤔

2022-09-08 03:33 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +protocol CalculateItem {
이 프로토콜도 파일을 따로 분리해서 관리하면 좋을 거같아요!

2022-09-08 03:33 UTC, jaemuYeo commented on Calculator/CalculatorTest/CalculatorTest.swift
> +    func testExample_수가_잘_들어가는지_확인하는_함수() {
테스트 함스의 네이밍은 입력과 과정 결과가 모두 들어가면 좋아요!
given when then 패턴처럼 말이죠
ㅇㅇ를 입력(또는 inqueue)하고 dequeue하면 결과는 ㅇㅇ이다

2022-09-13 02:21 UTC, eunho8713 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
상속을 받기위해서 클래스 타입으로 선언하였습니다.
배열에 들어올 값이 어떤 타입일지 모르기에 (정수, 실수, 음수 .. 등) 타입에 재한을 두지 않기위해 사용하였습니다.

2022-09-13 02:30 UTC, eunho8713 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
배열인 data는 다른 메서드를 통해서만 값을 추가하거나 삭제할 수 있고, 외부에서 메서드가 아닌 다른 방법을 통해 임의로 배열 값을 변경하지 못하도록 private으로 접근제어를 시켰습니다. 그렇기에 data 아래 메서드들을 public으로 선언한 것은 다른곳에서 인스턴스를 생성하거나 이 클래스를 상속받았을때 data배열에 값을 추가하거나 삭제시킬 수 있도록 메서드를 이용할 수 있게하기 위해서입니다!

2022-09-13 02:30 UTC, eunho8713 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var data: [T?] = []
배열에 nil값이 들어올수도 있기에 옵셔널 타입으로 선언하였습니다.

2022-09-13 02:30 UTC, eunho8713 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +protocol CalculateItem {
넵

2022-09-13 02:31 UTC, eunho8713 commented on Calculator/CalculatorTest/CalculatorTest.swift
> +    func testExample_수가_잘_들어가는지_확인하는_함수() {
넵 반영하겠습니다!

2022-09-13 05:09 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var data: [T?] = []
배열에 nil이 들어오는 경우는 어떤 경우가 있을까요?

2022-09-13 05:11 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
어떤 부모 클래스를 상속받으려고 했나요? 
프로토콜은 구조체와 열거형에도 채택이 가능합니다!

클래스는 참조타입인데 여러 곳에서 이 큐타입을 사용했을때 모두 같은 data배열에 접근한다면 어떻게 될까요?

2022-09-13 05:13 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
private 한 것은 너무 좋아요 💯
다만 우노와 또바기가 설명해준 다른곳에서 인스턴스를 생성하여 메서드를 이용하는 것은
default값으로도 충분합니다~ 접근제어의 default는 어떤 것인가요?

2022-09-13 05:18 UTC, jaemuYeo requested changes
우노 또바기~ 
간단한 코멘트 남겨놓았습니다!
해당 부분에 대한 것은 다음 프로젝트를 진행할때에 치명적일 수 있어서
꼭 짚고 넘어가야하기에 다시 반려할게요!
확인해본 후 반영할 부분이 있다면 진행해서 재요청 부탁해요 💪

2022-09-13 05:18 UTC, jaemuYeo commented on Calculator/CalculatorTest/CalculatorTest.swift
> +class CalculatorTest: XCTestCase {
테스트를 진행해보았다는 자체로도 이번 스텝에서는 성공입니다!! 👍
다음번에는 given when then 패턴을 이용하여 테스트의 흐름을 조금 더 명확하게 해보세요~
```swift
// 아래 주석은 허용입니다

func test_빈배열에_1을인큐하고_디큐했을때_디큐한값은1이다() {
    // given
    given에 대한 코드
    // when
    when에 대한 코드
    // then
    then에 대한 코드
}
```

2022-09-14 01:00 UTC, eunho8713 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
메모리관리가 제대로 이루어지지 못할것 같습니다. 다시 생각해보니 여러 곳에서 큐타입을 같이 사용하지 못하도록 구조체를 이용하는것이 더 효율적일것 같습니다!

2022-09-14 01:01 UTC, eunho8713 commented on Calculator/CalculatorTest/CalculatorTest.swift
> +class CalculatorTest: XCTestCase {
넵 반영하겠습니다!

2022-09-14 01:54 UTC, moonsoungjin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
internal 입니다 
명확한 접근 수준 수식어가 없다고 합니다

2022-09-14 03:13 UTC, moonsoungjin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var data: [T?] = []
0으로 나누기를 했을때의 NaN으로 표기하는 경우에 nil이 들어오는것 같습니다

2022-09-14 06:53 UTC, jaemuYeo reviewed
우노 또바기 고생헀어요~
스텝1 머지 진행할게요!! 아직 미완성인 부분이 있어
코멘트 꼭 확인 후 다음 스텝에서 반영해주세요!!
너무 늦어져서 다음 스텝으로 넘어가겠습니다 💪

2022-09-14 06:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
Queue타입은 구조체가 좋을 것같아요!
그 이유에 대해 한번 조사해보면 좋겠습니다!

2022-09-14 06:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var data: [T?] = []
0으로 나누었을때 표시해줄 NaN은 에러처리를 통해 해주면 돼요!
nil이 들어가지 않고 아예 값을 안넣어주면 되지 않을까요?

2022-09-14 06:53 UTC, jaemuYeo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public var count: Int {
아무것도 적지않는것이 internal입니다!
public들도 전부 internal로 해주면 좋을거같아요 😀

2022-09-14 06:53 UTC, merged